### ISSUE TITLE
Periscopeの評判を知りたい

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#104]
やってはみたものの、主催は評判ツイートとかそういうのみかけなかったので、本当にウケたのかよくわかってない。

**Comment by uzulla** [comment]
当日これなかったモズニオンから良かったとは聞いた。

**Comment by tsucchi** [comment]
trapple さんも良かったって言ってました。
https://twitter.com/trapple/status/749415431430033410

**Comment by uzulla** [comment]
「会場の外」の人ははたしてみていてくれたんだろうか、やっぱり告知不足だったかな〜
公式アカウントフォロワーそんなにいるわけでもないし、自分のTwitterでRTすればよかったか。

**Comment by uzulla** [comment]
まあ、やっぱり宣伝不足だし、あんまり視聴者数のびなかったな〜ということでとりあえずクローズ。
