### ISSUE TITLE
今回の質問方式はなかなか難しかったらしいけん

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#108]
ご意見を頂いた
- もっと煽らないといけないのでは？->煽りスクリプトをもっと書いたら？
- 質問ゼロだと、つらい
- セッションおわったら、壇上ではない所でやった方が良いのでは？

実際どうでしたかね

**Comment by kkotaro0111** [comment]
登壇者が「質問してくれたらステッカーあげる」ってやってたところがあったようで、それは好評だったみたいですね。
さすがに全登壇者にそういうの用意しろとは言えないけど、何かの参考になれば。

**Comment by hasegawa-tomoki** [comment]
質問ゼロはしかたないと思うけどねー。「トーク力を磨け」

**Comment by hasegawa-tomoki** [comment]
ふつうにマイクを回す方式よりカジュアルに質問できる感じで「これはアリだな」とは思いました。
ただ、「この時間にどこそこに行くとスピーカーがいます」という感じのやつでスピーカーへの質問を吸収しても良い気がする。

**Comment by uzulla** [comment]
良いという意見も、イヤだという意見も聞きますが、イイというのはまあさておき、
悪いというのは「うまくいった例を一度も見なかった」「そのまま壇上にたたせるのは酷である」「司会がもっと助け船を出せばいいのに」といった意見です。

司会の助け船は、それを私がきちんと想定し、スクリプトをかけばよかったので、単純に私が悪かった。反省して次にいかせそうです。

前者は「他の所だと、ちょっと別の所に移動させてやる」というアイディアがはせがわさん指摘の通りにありました。
ただ、そうなるとプロジェクタつかえないし、ほかの人にシェアできないけど
（まあ、実際今回もマイクでの復唱を（スクリプトには書いたつもりだったけど）やっていなかったらしいので、結果としてはかわらないかな）

まあとにかく（意識してなかったのですが）司会の力量に頼ってしまう設計だったので、私の想像力の欠如だったようです、イヤな思いをさせた登壇者がいただろうから、もうしわけないな…。

**Comment by uzulla** [comment]
やはり、先人には「そんなの歴然だろ、わからんのか？」という感じであり、私の脳内での小手先改善は「100年前に通過済みである」という感じがある。難しい、がんばろう。

**Comment by hasegawa-tomoki** [comment]
そうなんだ。
確かに誰も質問いない時の切り上げはスクリプトに書いたほうがよかったですね。
A部屋は比較的ワークしてたんだよね。

**Comment by mass10** [comment]
方式自体は良い。

C部屋は...

:smile:
- 結局、部屋全体がなし崩し的に質問コーナーになってしまった時があっておもしろかった。
- みんな結構質問してくれた。
- スタッフもちょっとだけ質問した。

:cry: 
- 質問が尽きたとき、もしくは一つも無かったときの切り替えが難しく、(自分が)登壇者を上手にエスコートできなかった点が心残り。あと「お疲れ様でした、ありがとうございました」を(自分が)きちんと言えなかった場面があった。
- こちらのMC力不足については、なかなか難しい課題でして...

**Comment by uzulla** [comment]
動画をみなおして、まあやっぱり普通の方法のほうがみんな馴染みがあるということがよくわかりました。
個人的には上意下達はすきでないので今回かえてみましたが、まあ、突然こうやってみれ、というのはむずかしい。登壇者に負荷のかからない方法でなんかないかなーと諦め悪くおもいつつも、まあ当座は普通が一番！という結論です。

ということでClose。
