### ISSUE TITLE
懇親会

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#11]
- [x] 6/9までに時間決定
- [x] 懇親会応募ページ作る http://connpass.com/event/33302/
- [x] 6/17までに出席数を確定する（出来るかな…

---

概要 https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/11#issuecomment-223277806

**Comment by makamaka** [comment]
下記の内容で店をあたります。
- 人数：80～100人
- 時間：19:30～20:30開始
- 予算：4000～5000円
- 場所：品川駅近辺（現在のところ）

**Comment by uzulla** [comment]
懇親会の開始にかかわるのがタイムテーブルのお尻ですが（まだくめてない）
終わって30分後くらいに懇親会開催となるように調整していきます。（ただし、店の距離にもよる）

あと、人数が結構多いので、開始よりも少し前に（30分くらい？）入り始める事ができるかきいてもらえるとたすかります。（でないと、2hのプランでも１hとかになっちゃう）

**Comment by uzulla** [comment]
あと、カード決済できるところがたすかりますね。
（ドタキャンが大量にでたときに、借金するのが楽なので）

**Comment by makamaka** [comment]
優先順位高めにあたります＞カード決済

**Comment by makamaka** [comment]
こちらで仮押さえしました。
http://tabelog.com/tokyo/A1314/A131403/13170829/

コースはまだ決めていません。リンク先みて要望等あれば。
要望がなければ2H飲み放題付全8品『花天-keten-』コース（4000円）に
しようと思います（その場合は手間とか初対面の人たちとのアレを考えて
しゃぶしゃぶでなくもつ鍋にします）。

時間については20:30にしてありますが遅くとも来週末までには最終的な時間を伝えることになっています。
時間の設定は5分刻みで可能
人数・コースの確定は6/17に伝えることになりました。ここまでに懇親会出欠確認必要！
10～15分ぐらいなら先に入ってもらっても大丈夫であろうと。
貸し切りではなく、ワンフロア内で通路を挟んで二つに分かれる
当日キャンセルは食事代のみ
前日までの変更であれば1,2名はOK
この宴会自体のキャンセルは6/10まで
カードはVISA, Master, JCB, Amex

**Comment by uzulla** [comment]
仮押さえ、何名になったのですかね？

**Comment by makamaka** [comment]
80～100で言ってあります。

**Comment by uzulla** [comment]
とりあえず、懇親会Compassを雑に立ててしまって、需要を見るというのはどうだろうか。

**Comment by makamaka** [comment]
良いと思います。
最初から定員100にするかまずは80で様子みるかどっちか良いんでしょうね？

**Comment by uzulla** [comment]
フォームは100でいいんじゃないかとおもわれ。

**Comment by uzulla** [comment]
http://connpass.com/event/33302/

**Comment by uzulla** [comment]
プロの宴会erに「えっ、料理（の人数）を少し少なめにするとかそういう交渉テクを駆使しないの？」と煽られるなど

**Comment by makamaka** [comment]
そんな交渉テクが……

**Comment by uzulla** [comment]
ということで、タイムテーブルがきまりましたので、懇親会開始時間を決められます。

18:30でよいのではないかとおもいますが、どうでしょうか。

**Comment by makamaka** [comment]
18:15に終わって、あと15分で大丈夫ですかね？

**Comment by uzulla** [comment]
あーそうですねえ…では18:45にしましょうか。

**Comment by makamaka** [comment]
5分ずれということで18:40でとれるか明日確認しておきます。

**Comment by makamaka** [comment]
18:40～になりました。

**Comment by uzulla** [comment]
今予約名は何になっているかわからないですが、イシダで結構です。

あと、当日、まかまかさんが最初にいって受け止めてくれる（＆すみやかに乾杯の練習までしてくれる）ということでよいですかね？
（私は追い出し確認などするので、多分ちょいおくれでいきます）

**Comment by uzulla** [comment]
「おかねをまきあげるほうほう」をきめないといけないなァ、俺がみんなに挨拶して握手しながらあつめていくかｗ

**Comment by makamaka** [comment]
予約は私の本名でやってありますが（最初「やっぱち」にしようとした）、まあそのままでも問題ないかと。
受け止め、了解です。

握手しながら集金方式、ちょっとみてみたいw

**Comment by uzulla** [comment]
本名公開OKでしたら、connpassに書くのでどうですか？

**Comment by makamaka** [comment]
では時間と名前入れておきますー

**Comment by uzulla** [comment]
人数100人まちがいなくいきそうなので、100人でOKではとおもいました。

**Comment by makamaka** [comment]
あー、もう100人超えますね。
もうちょっと増やせるかお店に聞いてみます。

**Comment by uzulla** [comment]
増やせる件口頭で聞きましたが、どうしましょね。

**Comment by makamaka** [comment]
今100人超えてて、枠増やせばさらに申し込み増えるのは間違いないでしょうが、
やぱっち抽選落ちた人は除く、とういことを考えると人数の把握難しいですね……
抽選枠に申し込んでる人とどれくらいかぶってるか突き合わせてみる必要あります？

**Comment by uzulla** [comment]
そうかそうなりますね、減るんだから100いかない気がしますね？仕組みをミスった気がすごいｗ

付き合わせてみる必要 is 私の財布（カード？ｗ）の心配ですね！
まあややこしい事になるんで、100のままで進めますか。

**Comment by makamaka** [comment]
そうですねえ……でも今週末まで時間ありますから、ぎりぎりまで検討したいと思います。

**Comment by makamaka** [comment]
100名、花天（4000円）コースにて予約。
鍋の味付けは後日で。

**Comment by makamaka** [comment]
来年のためのメモ：　飲み放題の内容は確認すること

**Comment by makamaka** [comment]
本日実際に食べてみて、醤油でよろしいですかね？＞参加者の皆さん

**Comment by mass10** [comment]
塩もよろしいかと

**Comment by uzulla** [comment]
実際醤油おいしかったから醤油でいいんでない？

**Comment by mass10** [comment]
おいしかったです！

**Comment by Shinpeim** [comment]
普通に美味しかったので醤油で良いのではないかと

**Comment by makamaka** [comment]
諸々意見を踏まえて、醤油でいこうと思います！

**Comment by uzulla** [comment]
これでタスク的には終わってるのかな？

**Comment by makamaka** [comment]
本タスクは終了でよいと思います。
あとはconnpassで通知したりtwitterで呼びかけるなどのタスク（#69）になっていきます。

**Comment by makamaka** [comment]
後ほど必要項目をWikiに転載しておきます。
