### ISSUE TITLE
忘れ物を解決する

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#110]
- [x] マウス
- [ ] キャノンのレンズキャップ

**Comment by kkotaro0111** [comment]
# マウス
- ルームB
- 登壇台
- 7/3 16:51
- 直近のセッション
  - https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/74 
  - https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/62
    - tarom に問い合わせたところ「僕が発表した時点で既に置かれてました。」とのこと

# キャノンのレンズキャップ
- ルームA
- 7/2 17:58
- https://twitter.com/yapcasia8oji/status/749165374747209728
- 直近のセッション
  - LT

**Comment by kkotaro0111** [comment]
マウスですが、録画見た限り、持ち主を特定するには至りませんでした。
というのも、そーだいさんのプレゼンが終わった直後にカメラにぶつかった人がおり、そこから2セッション分の登壇台が記録されておりませんでした。（その先には、taromがおり、その時点ではマウスはおいてあったらしい）

ただ、音や画面上のカーソルの挙動を見る限りでは、shokaiさんではないかな、と感じます
https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/94

**Comment by uzulla** [comment]
あらら、残念。了解です。
訊いてみます。

**Comment by uzulla** [comment]
よくかんがえたら全員にきけばよかったので、午後全員にIssue経由で質問してみた。

**Comment by uzulla** [comment]
マウスはみつかったっぽい（まだ送付先など確認できておらず
https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/91

**Comment by uzulla** [comment]
マウス発送しました。

**Comment by uzulla** [comment]
（レンズキャップェ…

**Comment by uzulla** [comment]
マウス到着とのこと。

**Comment by uzulla** [comment]
永遠にクローズできないISSUEになりつつあるので、とりあえずあきらめてClose。
