### ISSUE TITLE
当日の写真をzipか何かに固めてアップロードする

### ISSUE THREAD

**Issue by masawada** [hachiojipm/yapcasia-8oji-2016mid#113]
- 写真班の撮影した写真のうち，一部はPCに取り込みつつSDカードから削除していた
- ので，その分を固めてどこかにアップロードする

どこにアップロードするかご意見いただきたいです

**Comment by uzulla** [comment]
特にどこにアップロードでもよいです、最終的にFrickrにあつめるので、私（か、写真班）がうけとれればOKです
もしフリッカーになれていれば、あげてもらっちゃったほうが早いとおもうので、アカウント渡します。

**Comment by masawada** [comment]
https://dl.dropboxusercontent.com/u/3701574/yapc8oji/day1.zip
https://dl.dropboxusercontent.com/u/3701574/yapc8oji/day2.zip

**Comment by masawada** [comment]
2日分zipで固めてDropboxに置いておきました。お手数ですがダウンロードしてFlickrにアップロードいただきたいです。

このissueがcloseされるくらいまでは残しておこうと思います。

---

Flickrログインしてアップロード&しばらく放置したところ、なぜか途中でとまってしまいました、、

**Comment by t-kaga** [comment]
それたぶん自分が渡したものですね。
お渡ししたファイルも手元に残っているので気にしなくて大丈夫です！

**Comment by masawada** [comment]
あ、残ってたんですね。わかりましたーありがとうございます！
