### ISSUE TITLE
掲示物

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#12]
A4で、誘導を指示するもの。
当日手書きでもかまわないが、もし作れるのであれば。

**Comment by silfsquare** [comment]
@makamaka 
こちらも手伝えると思うので明日お話させてください〜！

**Comment by makamaka** [comment]
掲示物について
![20160412-171033-dsc035051033](https://cloud.githubusercontent.com/assets/127601/16233938/ef3ce0dc-380a-11e6-8fa0-6b602aba4c98.JPG)

ここに入れるものですが、フロアマップ(#27)使ってつくる感じでよいのかな？

**Comment by silfsquare** [comment]
これの印刷も承りますよー！
これ以外にも掲示物があればやります！

**Comment by makamaka** [comment]
ありがとうございます。よろしくお願いします！

**Comment by makamaka** [comment]
やったー！　案内板できたよ

---

![a](https://cloud.githubusercontent.com/assets/127601/16278142/b8d57054-38f0-11e6-998c-131f54dfd1a1.png)

---

![b](https://cloud.githubusercontent.com/assets/127601/16278158/cd52a858-38f0-11e6-9a05-e0bc299ce4c0.png)

---

![c](https://cloud.githubusercontent.com/assets/127601/16278184/e99fe714-38f0-11e6-8fe9-c4e25f5ea542.png)

---

![d](https://cloud.githubusercontent.com/assets/127601/16278196/f3522be6-38f0-11e6-87aa-21aa33d9e167.png)

**Comment by uzulla** [comment]
「このフロアマップはサイトにあるよ！」
ってかいておきたいｗ

**Comment by kkotaro0111** [comment]
案内板用に、上下逆のマップも用意しましょうか

**Comment by makamaka** [comment]
それはとても有り難いです＞上下逆マップ

**Comment by kkotaro0111** [comment]
[map_reverse.zip](https://github.com/hachiojipm/yapcasia-8oji-2016mid/files/333416/map_reverse.zip)
上下逆マップ用意しました。
大きめに書きだしたPNGと、編集に使ったAIファイルを入れてあります。

**Comment by makamaka** [comment]
ありがとうございます。助かります！

**Comment by makamaka** [comment]
@silfsquare 完成しました！　A4サイズでよろしくお願いしますー

[annaiban.zip](https://github.com/hachiojipm/yapcasia-8oji-2016mid/files/333460/annaiban.zip)

**Comment by silfsquare** [comment]
@makamaka 了解ですー！

**Comment by makamaka** [comment]
@silfsquare あ、すみません、まだダメでした！　しばしお待ちを！

**Comment by makamaka** [comment]
@silfsquare すみません、こちらでお願いします！

[Guide.zip](https://github.com/hachiojipm/yapcasia-8oji-2016mid/files/333462/Guide.zip)

**Comment by keima** [comment]
受付担当です。以下の紙を用意していただきたいです。
- [ ] A4:大きく数字の書かれた紙（ 0 〜 9 ） 各1部づつ 10枚
  - 受付窓口誘導に使用予定

データ（というほど大層なものではないですが）が必要であれば作成いたします

（誰にメンション投げたら良いだろう、 @silfsquare さんかな？ ）

**Comment by uzulla** [comment]
@keima これくらいなら、前日MSさんで印刷させてもらいます、他にも出すものはあるんで。
もしよろしければデータ（A4PDFかな）つくってください！

**Comment by keima** [comment]
@uzulla 了解です！作ります！

**Comment by uzulla** [comment]
@keima #78 のほうに転記しましたので、作成したらあっちにおねがいします。

**Comment by uzulla** [comment]
@silfsquare @makamaka
いまいち進捗みえてないんですが、これはsilfsquareさんがだして、当日もってくるということでいいんですかね？
A4出力だけなら前日にやっちゃうこともできそうですが。（ただ、PDFにはしてほしい）

**Comment by makamaka** [comment]
んー、これ @silfsquare さんが良い感じで（印刷紙の選定含めて）印刷してくれると想定しているのですが、そして当日持ってきてくださると考えてるのですが、この認識であってます？（これは #9 も同様に思ってます）

**Comment by uzulla** [comment]
@silfsquare ping

**Comment by silfsquare** [comment]
仕事が立て込んでるので木曜にぜんぶやりまするー

**Comment by uzulla** [comment]
無理せず！

**Comment by silfsquare** [comment]
@uzulla @makamaka @myfinder 
印刷用にトンボ入れたりしてるんですけどA4で大丈夫ですかね？
掲示物を入れる場所の写真を見るとA4より小さい気がするのですが。。。
いかがでしょ。

**Comment by myfinder** [comment]
A4でええよん

**Comment by silfsquare** [comment]
了解です！

**Comment by silfsquare** [comment]
一部返信忘れていましたが当日もっていきます！

**Comment by makamaka** [comment]
ではclsoeでよいですかね。
