### ISSUE TITLE
道案内コンテンツ

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#14]
- [x] ウェブページ（スマホでみれるもの）
- [x] 動画

**Comment by kkotaro0111** [comment]
品川駅から日本マイクロソフトのオフィスまで？

**Comment by uzulla** [comment]
品川駅からマイクロソフトジャパン様のエントランスまで、ですね。

**Comment by kkotaro0111** [comment]
例えばこういう表現も。360度で見回しながらルート確認できます。
https://www.youtube.com/watch?v=J4WVbI-JBzs

**Comment by uzulla** [comment]
これおもしろいーねー。これも貼ろう。

**Comment by uzulla** [comment]
http://yapcasia8oji-2016mid.hachiojipm.org/venue_info/
掲載しました。
