### ISSUE TITLE
写真

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#15]
- [x] カメラマンその１（主） @TakashiKaga  D800E + 24-70/2.8 (ストロボ無し)
- [x] カメラマンその２（副） @isuka [Panasonic DMC-LX100](http://panasonic.jp/dc/compact/lx100/)? [Canon 5D mark2](http://cweb.canon.jp/e-support/faq/answer/eosd/45374-1.html)?
- [x] カメラマンその３ （予備） @kkotaro0111  [Sony RX10M2](http://www.sony.jp/cyber-shot/products/DSC-RX10M2/)

---
- [x] 使用機材の確認（上に記入などで）
- [x] 撮影の取り決め > ひらたくいって、去年までのYAPCの写真を参考に
- [x] 腕章的なもの （スタッフ名札（赤色））
- [x] 撮影後にどこに写真を集めるか -> フリッカー

---
- 各登壇者、ブレたりしていないものが５枚以上。顔を上げている写真が２枚くらいはほしい（けど上げない人はいるので無理はせず）、アップと引きは適当に
- スピードライトの使用は控えめに（ぶっつけ本番なので、どうしても暗くてダメならつかうしかなさそうだが）
- 各部屋の状態も、１トークの度に何枚かほしい（これは適当でもよい）
- 受付も、毎日朝一だけでいいので10枚くらいはほしい、並ぶとおもうので、その雰囲気が見えれば良い
- ラウンジは被写体の人が偏らない感じでまんべんなくほしい。
- （もし懇親会にくるなら）多少懇親会もとってほしい（ほかのお客さんがはいらぬように）。
- あと、スタッフの人も撮ってあげてほしい、準備はほとんどないはずだけど、準備してる風景とか、ネット担当部屋とか。
- 枚数はいくらあっても多い分には良いです。
- なお、撮影した写真は最初非公開でおねがいします。
- 良い感じのがあれば、ネット担当にまわしてもらえるとたすかります。
- まあ、無理せず。

**Comment by t-kaga** [comment]
主担当やりますよー！

**Comment by uzulla** [comment]
@TakashiKaga ありがとうございます！
ではお願いさせていただきます！

**Comment by kkotaro0111** [comment]
俺も俺も

**Comment by kkotaro0111** [comment]
【参考】去年までのYAPC
http://30d.jp/yapcasia/6
http://30d.jp/yapcasia/8

**Comment by kkotaro0111** [comment]
# 撮影後にどこに写真を集めるか

一旦、30days でいいかな。内部的に。
その後、載せる写真のピックアップ（というより載せない写真のドロップアウト）をして、
Flickrに移行させるとか。

**Comment by t-kaga** [comment]
自分はFlickrを使いたいです。
もし30daysを使い慣れているというのであれば、そちらにもアップするような感じでいかがでしょう？

**Comment by kkotaro0111** [comment]
30daysは無期限公開にするには有料（月額制）なので、あくまで「写真の回収」を目的にしてます。
なので、別の方法で回収するのであれば、30days使わずに、そのままFlickrで良いと思います。

**Comment by isuka** [comment]
@kkotaro0111 
副担当どうしましょう？変わりますか？
// slackで応答しただけだったので

カメラ：Panasonic DMC-LX100

**Comment by kkotaro0111** [comment]
@isuka 
できれば変わっていただけると助かります。
どちらにせよ、俺も写真は撮りますが、徘徊は出来そうにないので。

**Comment by isuka** [comment]
@kkotaro0111 
了解です。では副担当やります。

**Comment by uzulla** [comment]
暗所撮影になるし、俺の5Dmk2だそうかしら？
ちょっとコンデジではむずかしいシチュエーションだとおもいます。

（よくかんがえたら俺はまちがいなくウロウロするし、俺も撮影すればいいのか？ｗ）

**Comment by isuka** [comment]
ストロボは買おうと思ってますが、そもそもフラッシュ撮影ってどうなんでしょう？

とはいえ一眼程の性能は無いので、借りられるならその方が安心かもしれないです。( 一日目は両方使って様子見るとか)

**Comment by uzulla** [comment]
@isuka ストロボは（使い方になれている人でなければ）利用不可とさせてくださいー。聴講者の方が「邪魔だな！」とおもってしまうと思うので。

カメラの性能ですが、レンズF値にもよりますが、SSは案外あげないといけないので、ISO6400〜8000くらいは必要とおもいます。そこでノイズがめだたなければ大丈夫です。

**Comment by uzulla** [comment]
機材は事前に送る事ができるとのことなので、
当日持ち込みをしたくない場合にはあつめますので、皆さん早めに言ってください。

**Comment by t-kaga** [comment]
機材忘れてました
機材：D800E + 24-70/2.8 (ストロボ無し)

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E5%86%99%E7%9C%9F%E6%92%AE%E5%BD%B1%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
に転記したので、クローズします。
