### ISSUE TITLE
録画

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#16]
確保物資
- [x] A用カメラ - 石田私物 SONY CX670
- [x] A用ACアダプタ - 石田私物
- [x] A用メディア - 石田私物 64GB microSD
- [x] A用三脚 - 石田私物
- [x] A用コンセント延長ケーブル - 石田私物
- [x] B用三脚 kkotaroさん
- [x] B用カメラ kkotaroさん私物 PJ790V
- [x] B用メディア （カメラ内蔵のもの）
- [x] B用ACアダプタ kkotaroさん私物
- [x] B用コンセント延長ケーブル kkotaroさん私物
- [x] C用三脚 isukaさん
- [x] C用カメラ shimpei氏私物
- [x] C用ACアダプタ shimpei氏私物 HDR-CX430
- [x] C用メディア uzulla私物（フルSD、64GBくらいの
- [x] C用コンセント延長ケーブル uzulla私物
- [x] D用三脚 uzulla私物 cube
- [x] D用カメラ uzulla氏私物 ivis X
- [x] D用ACアダプタ uzulla USBケーブル＋ACアダプタ
- [x] D用メディア uzulla SD 64GB
- [x] D用コンセント延長ケーブル uzulla私物

※Dは飛び入りトラック
- [x] 動画担当者決める kkotaro & uzulla

---
- 運用としては、まわしっぱなしにする。トーク間で録画をOn Offするのをわすれたりミスを防ぐため
- 画質は720pで、圧縮率高めで良い
- スクリーン優先、人は入らなくても良い（人は写真で抑える）、すくなくとも中央に大きくスクリーンをおさえないと、自動露出がうまくうごかないと思われる。
- デモは、余裕があればうまいこと撮影するが、無理はしない

**Comment by isuka** [comment]
三脚は1.5mくらいの高さになる奴があります。
3mくらい？のOAタップで良ければこちらも持っていけます。
カメラはコンデジですがPanasonic DMC-LX100とかで良ければ64GBのSDカードと一緒に持っていけます。
DCカプラはありますが、21000mAhくらいのバッテリで使っているので持続時間が足りないようならアダプタは用意します。

**Comment by uzulla** [comment]
ここでのカメラはビデオ撮影用のカメラなのですが、できれば一日中操作無しに連続して撮影できることが必要です。
しかし、大抵のデジタルカメラの動画撮影機能は輸出関税の都合で三〇分までしか連続撮影ができません。LX-100も同様のようです。（注意書きの箇所にあります）

三脚については是非検討させてください！

**Comment by isuka** [comment]
なるほど。了解しました。
用途に沿わず申し訳ないです。

**Comment by uzulla** [comment]
いえいえ、本当に助かりマス！三脚だけでもお願いする事になるとおもいます！ :bow:

**Comment by mass10** [comment]
「機材藩」 という人たちがいます。生中継が得意っぽいです。

http://kizai-han.wjg.jp

参考まで

**Comment by isuka** [comment]
三脚ですが、サイズの参考まで。
![p_20160522_114815](https://cloud.githubusercontent.com/assets/733284/15451871/98b13696-2013-11e6-9d43-d7d5fbe75e4b.jpg)

**Comment by kkotaro0111** [comment]
三脚ですが、俺もスチル用のがあるので、それで良ければ使えます。
それをB用三脚にして、isukaさんの三脚はC用にしてはいかがでしょうか。

**Comment by kkotaro0111** [comment]
コンセント延長ケーブルもあります（どれくらいの長さが必要かにもよりますが）。
B用コンセント延長ケーブルは、それが使えます。

**Comment by kkotaro0111** [comment]
カメラですが、 SonyのPJ790Vになります。
http://www.sony.jp/handycam/products/HDR-PJ790V/spec.html
内蔵メモリ(96GB)があるので、それでよければ一番いい画質※で7時間くらい撮れるそうです。

外部メディアは、SD/SDHC/SDXCメモリーカードが使えます。
一番いい画質※だと、64GBので5時間くらいですかね。
720p / 30fps / MP4 でよければ、32GBのでも10時間くらいは撮れそうです。

※ 1080p / 60fps / AVCHD

**Comment by uzulla** [comment]
> 三脚

了解です、そのようにしましょう

> コンセント延長ケーブルの長さ

コンセントについては、あらゆる床にコンセントがあるので大丈夫だとおもいます。
6/4にすこしチェックしましょう。 #25

> カメラ貸していただく件

ありがとうございます、過去のYAPCでの経験上720pで十分ですので画質をおとして時間を稼ぎたいと思います。そうなれば多分内蔵メモリだけでも行けそうですね。

なお、カメラ等についての預かりは、現地には物がおいておけないので、私は五反田のホテルに陣取るのでそこに置いてもらおうと思います。
（勿論毎日朝もってきてもらってもOKです）

**Comment by uzulla** [comment]
動画担当者決めたいんですけど、 わたし と @kkotaro0111  でいいですかね？
動画でなにかあったら聞かれる役目、ということです。セッティングとかも。
ほかにもビデオカメラ操作ができる人がいるなら、聞いておきたい。

**Comment by uzulla** [comment]
（うっかりクローズ :bow:

**Comment by kkotaro0111** [comment]
> shinpei0213 [4:58 PM] 
> ビデオカメラ貸します

https://yapc8oji.slack.com/archives/random/p1465027108000455

**Comment by uzulla** [comment]
@Shinpeim 
貸してもらうビデオカメラなんですが、

 C用ACアダプタ
 C用メディア
 C用コンセント延長ケーブル

ここらへんだせますかね？

**Comment by Shinpeim** [comment]
ちょっとお家かえってから確認します

**Comment by Shinpeim** [comment]
ACアダプタは大丈夫です。

延長ケーブルとメディアについてはちょっときょうもう力尽きたんで明日確認させてください

**Comment by Shinpeim** [comment]
![image](https://cloud.githubusercontent.com/assets/876988/15861925/e68e6314-2d08-11e6-914b-2180d4b8d26a.png)

**Comment by Shinpeim** [comment]
あと延長ケーブルも余ってるやつなかったです……

**Comment by Shinpeim** [comment]
しんぺい私物カメラ
- Sony HANDYCAM
- 型番: HDR-CX430

**Comment by uzulla** [comment]
機材は事前に送る事ができるとのことなので、
当日持ち込みをしたくない場合にはあつめますので、皆さん早めに言ってください。

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E9%8C%B2%E7%94%BB%E9%96%A2%E9%80%A3
に転記した。
