### ISSUE TITLE
ボランティアスタッフ確定

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#17]
- [ ] 連絡先収集

**Comment by hypermkt** [comment]
既に検討済みかもしれないですが、必要そうな項目ってこれでしょうか？

### 必要な項目
- 氏名（よみがな付き）
- Googleアカウントのメールアドレス：Googleスプレッドシートを関係者のみに共有するため
- GitHubアカウント：GitHubアカウントと氏名を紐付けるため
- LINEアカウント：当日の連絡用
- 電話番号：当日の連絡用
- 写真（あれば）：完全にメンバーの顔と名前を覚えたわけではないので、あるとたいへん助かると思います。

### 収集方法
- Slack上でDMで聞く

**Comment by uzulla** [comment]
#32 に委譲
