### ISSUE TITLE
開催日に必要な備品

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#2]
確保完了
- VGAアダプタｘ１（uzulla私物）
- VGAアダプタ x 1 （silfsquare私物、石田が受け取り済み）
- VGAアダプタ x 1 (kkotaro)
- 養生テープｘ2 (uzulla
- 適当なハサミ (uzulla
- 適当なカッター (uzulla

確保できてない
- [ ] 掲示物 #12 
- [ ] 通行止めサイン #9 
- [x] キッチンペーパー（人は飲み物をこぼすので）
- [x] ゴミ袋（基本上記のためだけに）
- [x] 救急箱（絆創膏、ガーゼ、包帯、三角巾（？）、消毒液（？）、ビニール使い捨て手袋）
- [x] 名札入れ、名札カード
- [x] マーカーペン（10本くらい はせがわさんのところにおくった
- [x] ビニルヒモ、封鎖や、入館証まとめに
- [ ] 録画機材 https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E9%8C%B2%E7%94%BB%E9%96%A2%E9%80%A3
- [ ] 撮影機材 https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E5%86%99%E7%9C%9F%E6%92%AE%E5%BD%B1%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
- [ ] 着払い 返送用送り状＆段ボール

**Comment by silfsquare** [comment]
![img_20160510_151418](https://cloud.githubusercontent.com/assets/6573249/15137150/b808f74a-16c2-11e6-9ca3-3652ad612075.jpg)
@uzulla これですよね？
これで良ければ出せますよー

**Comment by uzulla** [comment]
ありがとうございます！宜しくお願いします！

**Comment by silfsquare** [comment]
#9 #12
この辺りは手伝えるかもしれません〜！

**Comment by uzulla** [comment]
@silfsquare 
そこの箇所、もし手伝えそうなら、そちらのISSUEにかいてください！
なお、いまのところ担当はmakamakaさんです。

**Comment by uzulla** [comment]
養生テープをamazonした

**Comment by uzulla** [comment]
あらかた発送した。

**Comment by uzulla** [comment]
ほかのものはほかのISSUEにヒモ付くので、このISSUEをクローズ
