### ISSUE TITLE
チャットを用意する

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#23]
当日の連絡などにもつかうので、スマホのクライアント（プッシュ通知）が必須。
- Slack（高い…（ログ検索しなければ良いけど））
- idobata（あまりつかったことがない）

---

悩みましたがslackになりました。
後日また告知しますが、以下URLから自分にInvitationを送れます。
https://yapc8oji-slack-auto-invitation-form.arukascloud.io/

**Comment by Shinpeim** [comment]
ログ検索せず、issueにしたほうがいいものはガンガン issue に転記していくのはどうか、というのがあります

**Comment by uzulla** [comment]
解るのだけれど、「運用でカバー」的手法は実現の難易度（工数）が結構たかくて困る。
あとは邪道だけど、外部にログを転送するソフトも検討はできるとはおもっています。
（けど、これって案外不便なのよね。モバイルでサッと見たいからこそ…なので）

**Comment by Shinpeim** [comment]
なるほど……難しい……

**Comment by uzulla** [comment]
典型的な「猫の首に鈴をつける」問題。

**Comment by hasegawa-tomoki** [comment]
検索、ログが流れない分ならOKだけど、まずは今年分、とかだったらSlack無料でも良い様な気はしますねえ。
Slackは所詮フローな情報なので、ストック的な情報源は必要になるんじゃないですかねー。
そして、GitHubもあるので、Wikiになる、みたいな。

**Comment by uzulla** [comment]
上にも書いた通りですが、運用でカバーするのは、いつか転記するのをわすれるので、ログは重要なのですよね。後、前後の経緯も読めるとたすかるのですよ（転記が上手い人なら問題ないでしょうけど）。
ながれない分なら〜というのも、10000って案外あっという間に終わるんですよね。

という事で、「流れないなら」、「ストック情報源を用意すればいい」というのは、私の心配しているポイントとはちょっと違うんですよね〜。

とはいえ、二人連続でストックでいいじゃんといわれたので、きっとみんな大丈夫なのかな〜☺️

**Comment by hasegawa-tomoki** [comment]
ログとして前後関係含めて取っておきたいキモチはすごくわかる。
「当日の連絡などにもつかうので、スマホのクライアント（プッシュ通知）が必須」という意味では無料Slackでいいな、と。
それとは別にストックはストックで中長期的な運用を考えたら重要かなーと思います。

**Comment by uzulla** [comment]
とりあえずslackをつくってみた。
自動招待フォームもつくった。
https://yapc8oji-slack-auto-invitation-form.arukascloud.io/
どなたかちゃんと登録できるか試して頂けませんでしょうか。

**Comment by Shinpeim** [comment]
フォームsubmitしたらnot foundになりました

**Comment by hasegawa-tomoki** [comment]
おなじくー！

**Comment by uzulla** [comment]
おおう、なおしました（Docker情弱です

**Comment by uzulla** [comment]
無事に動いたことが確認できたのでクローズ。
