### ISSUE TITLE
ベストトーク賞を作る

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#24]
- [x] 何位まで？ 3位まで
- [x] 授賞式をタイムスケジュールに載せること ＞ 最後閉めの一言の時にシュッとやろう
- [x] 投票システム
- [x] リンクを張る
- [x] 副賞
- [x] 促す自動ツイート

**Comment by uzulla** [comment]
投票システムはGithubのReactionでいいのではと思いつつも、あまりスマホフレンドリーではないからやっぱりつくらないとダメかな…と思っている。

**Comment by hasegawa-tomoki** [comment]
（重複投稿を防ぐ仕組みが欲しい場合、connpassの受付番号がおおむね使える。）

**Comment by karashi39** [comment]
副賞案：書籍

個人的にはACME大全全巻セットが欲しい
(スピーカーの人はすでに何冊か持ってるかもしれませんが)

**Comment by myfinder** [comment]
別途スタッフチャットでお伝えしますがMSからご協力できることがいくつかあります。

**Comment by uzulla** [comment]
1位についてはがんばって良い感じをの注文done

**Comment by uzulla** [comment]
（おもったのだが、7/3日の夜に決定するじゃん？7/2にしかきてない人だったらどうしよう…ｗ）

**Comment by hasegawa-tomoki** [comment]
（通しにしなかった後悔+1案件ですなあ。）

**Comment by uzulla** [comment]
キャパ1000人の会場なら通しでもいいなｗ

**Comment by uzulla** [comment]
ヒヤヒヤしてたんだけど、１位の人のメインブツがとどいた

**Comment by uzulla** [comment]
ReactionがGithubのモバイルページからは表示もできなきゃ当然設定もできなかったので、実装した。

最終的にはISSUEか、タイムテーブルからリンク貼る。

**Comment by uzulla** [comment]
ベストトーク賞のサーバーをたてて、SSLをいれて、セキュリティ検査などをした。

![image](https://cloud.githubusercontent.com/assets/870716/16383176/f8f8b58e-3cbe-11e6-992e-f431bb5dc5dc.png)

![image](https://cloud.githubusercontent.com/assets/870716/16383179/fbbadc02-3cbe-11e6-8755-04913ec2c817.png)

![image](https://cloud.githubusercontent.com/assets/870716/16383180/ff8e7cc6-3cbe-11e6-8495-f45dcd1dae80.png)

**Comment by uzulla** [comment]
タイムテーブルからリンクを張った。

とりあえず大体できたのでClose
