### ISSUE TITLE
6/4 打ち合わせスレ

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#25]
# ギ題
- [x] 自己紹介、経験確認
- [x] お部屋リーダーを募る
  - [x] エスカレーション図 −＞連絡先あつめたりする  #34 
- [x] 下の受付募る
- [x] カメラマン募る
- [x] 当日の連絡手段（Slackで良いか？）
- [x] slackの電話ってホントにモバイルでもつかえんの？ > なかったことに
- [x] slackの電話って複数端末もってる人はどうなるの？ #34 
- [x] スタッフ認識票グッズみたいなのいる？ #35 に委譲
- [x] みんなが不足機材かしてくれないかお頼み
- [x] 現在のトーク応募の採択についてご意見交換 
- [x] なんとなくカメラ位置を確認する
  - [x] 石田がビデオカメラをもっていく
- [x] 「ウオオ！俺はパッションがあるぞ！」あるいは「暇ならあります」の人がいるか聞く
- [x] 石田が一応VGAアダプタもっていく
- [x] フロア地図を印刷しておく
- [x] フロア地図に避難経路を記入して非難地図を作る
# スタッフの方がおぼえる事
- 場所
- 会場の構造
- 設備（スクリーンなど）
- スタッフ同士の顔
- 災害時避難経路の確認
- 連絡網（エスカレーション）
- 防災上の縛りの有無（収容人数）

(追加中)

---

http://connpass.com/event/32685/

**Comment by myfinder** [comment]
災害時、並びに人災時の対応についても。

**Comment by uzulla** [comment]
@myfinder 
災害時の避難経路（非常口など）や、防火シャッター位置が記載されたマップの用意をお願い出来ますか？（画像データでよいです）
（今回展示物はないので、防火シャッター位置はそこまで問題にはならないはずですが、一応）

もし、なんらか過去に利用した防災時資料があれば、それもいただけるとたすかります。

**Comment by myfinder** [comment]
そういったマップはありませんが、避難経路となる階段の位置については6/4の打ち合わせの際にスタッフ全体へ案内します。
また、以前お渡ししたフロアの図でも説明をしますのでそれで把握してもらえればと思います。

**Comment by timakin** [comment]
お部屋リーダー

```
kkotaro0111
karashi39
hasegawatomoki
hypermkt
shinpei0213
timakin
pocket7878
motchang
```

受付

```
konnkonn
takakiku810
62jun26
wata727
```

カメラマン

```
kkotaro0111
```

**Comment by timakin** [comment]
ビデオカメラ(Sonyハンズカメラ)

```
shinmei0213
```

**Comment by timakin** [comment]
#27 
#31 
#32 
#33 
#34 
関連issues

**Comment by uzulla** [comment]
timakinさんがかいてくれたことは各々にコピペしたので、本スレはクローズします。
