### ISSUE TITLE
フロアマップ

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#27]
- [ ] サイト（スマホでみれるもの）
- [ ] 行動範囲がわかる
- [ ] トイレがわかる
- [ ] 緊急時の避難経路がわかる

**Comment by myfinder** [comment]
ランチは1F,B1Fのグランパサージュにいろいろあります
http://www.shinagawa-grandpassage.jp/shops
これも案内に入れていただけると参加者がランチ難民にならずに済むかと。

**Comment by kkotaro0111** [comment]
うぇーい

**Comment by kkotaro0111** [comment]
![2016-06-04 17 24 05](https://cloud.githubusercontent.com/assets/1256392/15799514/9647bc4a-2a9a-11e6-931b-53e26ca30c71.jpg)
![2016-06-04 17 24 15](https://cloud.githubusercontent.com/assets/1256392/15799516/9c839f84-2a9a-11e6-89e1-ea3de8ded7bb.jpg)

**Comment by uzulla** [comment]
![image](https://cloud.githubusercontent.com/assets/870716/15800737/78cb7536-2abc-11e6-859c-d2b15a6e5b65.png)
C+Dとかいてはありますが、これはC会場ということで良いとおもいます。
（Cが一番広いのだが、まあ混乱するし、Cでよいでしょ）

スタッフ控えと、アンカンファレンスは決定してないんで、とりあえずは記載無くてOKと思います

**Comment by uzulla** [comment]
[マイクロソフト様会議室見取り図＿SGT31F.pdf](https://github.com/hachiojipm/yapcasia-8oji-2016mid/files/298923/SGT31F.pdf)
見取り図元ファイル

**Comment by karashi39** [comment]
簡単なのを作ってみました。出来はよくないと思いますが、一応アップします。

![image](https://cloud.githubusercontent.com/assets/12491692/15823573/3bb8b20a-2c36-11e6-9e37-8bdd0c03bbd8.png)

**Comment by motchang** [comment]
Lounge C は当日入れなくなる運用だったと思うので緑が相応しいかと…！

**Comment by hasegawa-tomoki** [comment]
Lounge C、入れなくなるのは（この図で言うと）左側半分ぐらい、ですね。（真ん中あたりにあるカウンターの奥）

**Comment by karashi39** [comment]
そうでしたっけ…ちゃんと把握してなくてすみません！他にも修正点があるかもしれないので、まとまった時点で修正します。
また、かなり雑な図で、一般参加の人に配れるレベルなのか怪しいので、私よりアビリティに溢れる人が良いものをキシリア様に届けてくれることを期待しています！

**Comment by kkotaro0111** [comment]
![sgt31f](https://cloud.githubusercontent.com/assets/1256392/15865523/1014f740-2d16-11e6-93b4-2305b02730c5.png)
まだいじるけど、表現としてはこんな感じ？
モノクロ印刷できる、シンプルなものも必要かもしれない。

**Comment by uzulla** [comment]
@kkotaro0111 
良いとおもいます。

もうちょっとフォント大きくできるとうれしいかなとおもいます（スマホの画面でみれる程度に）。

非常口などは日本語表記でもよいとおもいます、また、EVのFor Guestは（そのままだと意味が通じにくいので）なにか変えるか、無くて良いとおもいます…がどうだろう @myfinder

白黒で表現できればベターですが、まあそこまでコダワリはないです、みんなスマホでみるだろうし。

（そうねーラウンジだよなー、ホワイエだけど…（独り言）普通の人はホワイエいわないもんなｗ）

一部はもうすこし簡略化してよいとおもいます（非常口とトイレは特に、位置がわかれば、中の構造は適当でよい）

セミナールームA等の表記は「ルームA」でよいです。

あと、 @Shinpeim の飛び入りはどこにくるかな、くらいですね。

**Comment by kkotaro0111** [comment]
ホワイエ、ところがどっこい、Microsoftさんのフロアマップでも「ラウンジ」表記なんですよね。

**Comment by Shinpeim** [comment]
飛び入りトラックが31C-13に確定しました。締め切りとしていたCのラウンジの扉を開放し、そこを通っていく感じです

**Comment by kkotaro0111** [comment]
![2016-06-08 17 07 42](https://cloud.githubusercontent.com/assets/1256392/15887147/8cd6b798-2d9b-11e6-9a66-5247e3df3c82.png)

> 立ち入り禁止境界は、C-20の下でOK？

---

> Corridorってかいてあるとこらへんで

**Comment by myfinder** [comment]
@uzulla 反応遅れました。EVは混雑時はさておき基本は来客用をお使いいただきたいのでそれがわかるようにしていただければ良いです。

**Comment by uzulla** [comment]
ならばひねらず元のままゲスト用EVで良いですね、了解です。

自分で言っておいてすいませんが、そんな感じで @kkotaro0111

**Comment by kkotaro0111** [comment]
![sgt31f](https://cloud.githubusercontent.com/assets/1256392/16169966/73910fac-357c-11e6-8503-71e6e765f784.png)
修正しましたー

**Comment by uzulla** [comment]
よいとおもいますが、個人的にはビルと空（空中）の色の差はもうちょっとついててもいいのでは（一瞬みえなかった）

あと、必須修正点として、封鎖場所がちょっと変更されて、トイレはEV前の通路からのみいけるように（出口で左右まちがえたら？ってかんがえるとやっぱり元のほうがいいかな？ @myfinder )、あと、Dの上の封鎖はわかりづらいんだけど、線のように封鎖になります。
マークを移動するだけでよいとおもいます。
![73910fac-357c-11e6-8503-71e6e765f784](https://cloud.githubusercontent.com/assets/870716/16172398/27b04962-35c3-11e6-9f69-ccc841141a4a.png)

あと、この緑線のところが実際は「ドア」であり、これがこの図だと（壁の縦線がズレてるので）廊下にみえるので、ちょっとわかりづらいかな…という感じがあります、。

この写真は「ラウンジC」のCあたりから、緑の線でかいたドア方向をみている写真

![_2016_06_19_2_12](https://cloud.githubusercontent.com/assets/870716/16172405/5a134724-35c3-11e6-9930-2a5a5132af89.png)

表現むずかしいとおもうので、縦の壁（の線）をそろえるだけでもいいかなあ。

**Comment by myfinder** [comment]
@uzulla 確かに左右間違えるのよくあるので元のままでいいと思いました。

**Comment by isuka** [comment]
細かいですが、Room Dの右側はガラス張りで入れませんでした。
![27b04962-35c3-11e6-9f69-ccc841141a4a](https://cloud.githubusercontent.com/assets/733284/16174848/21a9415a-3612-11e6-9d92-a00aa92c571d.png)

**Comment by tsucchi** [comment]
Room Dは正式名称(31C-13)も書いた方がいいかも、と思ったのですが、どうでしょう？

**Comment by uzulla** [comment]
roomDの様子です、これたしかに開かないんだっけかな？

![_2016_06_19_19_19](https://cloud.githubusercontent.com/assets/870716/16176784/ca0296f4-3652-11e6-98db-37178dfe10e9.png)

**Comment by myfinder** [comment]
@uzulla @kkotaro0111 31C-13の写真向かって右側は開きません。

**Comment by uzulla** [comment]
![73910fac-357c-11e6-8503-71e6e765f784-1](https://cloud.githubusercontent.com/assets/870716/16176805/f3a3e9c6-3653-11e6-81c1-acc83e173b67.png)

ということで、最終的にはこうじゃ

（縦線をつなげるとき、Lounge C側を全体的に左にずらすような感じがよいとおもわれる）

**Comment by uzulla** [comment]
「31C-13」ってかくのはよいとおもうけど、まあ、某さんに立っていてもらうから、そんな迷わないのでは。

**Comment by uzulla** [comment]
概ね画像としてよさそうなので、一端掲載しました。

http://yapcasia8oji-2016mid.hachiojipm.org/time_table_7_2/
（等）

**Comment by kkotaro0111** [comment]
遅くなりましたー

全体マップ。ピンチアウトで拡大してみられるように、大きめに書き出しました。
<img width="605" alt="1 2x" src="https://cloud.githubusercontent.com/assets/1256392/16272329/5b90a75a-38d8-11e6-9399-6cb17d21ad30.png">

ピンチアウトしなくても、も少し大きめで見られるように、
不要部分（建物右側のスペース）をクロップしたものも用意しました。
![2](https://cloud.githubusercontent.com/assets/1256392/16272375/8c8ba526-38d8-11e6-981f-fde93182275a.png)

お好きな方をお使いください。

**Comment by uzulla** [comment]
ありがとうございます！
どうせなので、クロップ版のほうをつかおうとおもいます。

よさそうなので、これでクローズします。（なにかあれば、またオープンします）
