### ISSUE TITLE
参加応募ページ

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#29]
- [x] 人数とか決める  250 ≒ 55(登壇者)＋14(LT)＋30(スタッフ)＋150(一般枠)
- [x] アンケート内容
- [x] 懇親会についてリンク http://connpass.com/event/33302/
- [x] 説明テキスト
- [x] 作成する
- [x] 道案内コンテンツへのリンク

---
- スタッフ
- 登壇者
- LT者
- 先着聴講者
- 二日分作るのを忘れずに

---

アンケート内容
- お名前（必ずご本名をフルネームで（漢字の本名ならば漢字で）、会場の入館証発行の為に必要です）
- 所属（会社名や学校名等、自営業の方は自営やフリーランスと記入ください、会場の入館証発行の為に必要です）
- メールアドレス（会場の入館証発行の為に必要です）
- ここまでは入館に必須名項目でしたｌありがとうございました。
- ここから以下は運営陣が今後どうしていくか道しるべになるアンケートです。それ以外には利用いたしませんので、可能名範囲で本当のトコロをおしえてくだい！
- 貴方の、主なSNSアカウントのURLを宜しければお教えください、Twitter, githubなど。
- このイベントをどこでご存じになられたか是非お教えください
- 過去にYAPCに参加したことがありますか？あれば是非年度などお教えください、複数回答可です
- 主要な開発言語をお教えください（Perl, Ruby, Python, PHP, Java, C# 等複数回答可です
- 普段お使いの開発環境をお教えください（Mac, Windows, Linux 等、複数回答可）
- 主なサービス運用環境をお教えください（CentOS, Ubuntu, RHEL, Debian, Amazon Linux, Windows Server  等、複数回答可）
- 主なサービス運用インフラをお教えください（AWS, さくらのVPSやクラウド, GCP, Lolipop, オンプレ, Azure 等、複数回答可）
- 普段開発に使っているツールやサービスをお教えください （github, jenkins, CircleCI, Redmine, Qiita team, Slack, Confruence 等、複数回答可)
- 技術情報を知る際に参考にしているメディアを教えてください(Qiita, はてブ, Twitter, WEB+DB Press, Software Design,  Rebuild.fm 等、複数回答可)
- よく参考にしているサイトやSNSアカウントがあれば是非教えてください（Twitter, Facebook, Qiita などのURL 等、複数回答可）
- 興味がある分野などがあれば簡単でかまいませんので是非お教えください。
- あなたの年代をお教えください（10代, 20代, 30代, 40代 等 ）
- あなたの職務上の役割をお教えください（プログラマ, インフラエンジニア, デザイナー, マネージャ, 役員, 王, 全部 等、複数回答可)
- 長々とすみませんでした、是非楽しいイベントにしましょうね！

**Comment by myfinder** [comment]
先着だと即埋まってしまう気がするので、抽選を基本にしたほうがいいのではと思いました。

**Comment by myfinder** [comment]
アンケート内容
- 開発言語(Perl, Ruby, Python, PHP, Java, C#, etc)
- サービス運用環境のOS(CentOS, Ubuntu, RHEL, Debian, SUSE, Windows)
- 開発環境のOS(Mac, Linux, Windows)
- インフラ(AWS, さくらのXX, オンプレ, Azure, etc)
- 開発に使っているツールやサービス(github, jenkins, circleci, etc)
- このイベントをどこで知ったか
- 技術情報をどこで仕入れているか(WEB+DB, SD, Qiita, etc)
- よくウォッチしているアカウント(twitter, FB, etc)
- 年代(10代, 20代, 30代, それ以上)
- 役割(プログラマ, インフラエンジニア, デザイナー, マネージャ, 全部, etc)

このくらいあるといろいろ可視化されて面白いのではと思いました。

**Comment by uzulla** [comment]
- お名前（必ずご本名をフルネームで（漢字の本名ならば漢字で）、会場の入館証発行の為に必要です）
- 所属（会社名や学校名等、自営業の方は自営やフリーランスと記入ください、会場の入館証発行の為に必要です）
- メールアドレス（会場の入館証発行の為に必要です）
- SNSアカウントなど（よろしければ）

**Comment by uzulla** [comment]
アンケート内容、必須にするか、非必須にするか悩むな。

**Comment by uzulla** [comment]
道案内へリンクしたのでクローズ
