### ISSUE TITLE
twitterや、サイトで使えるロゴ

### ISSUE THREAD

**Issue by makamaka** [hachiojipm/yapcasia-8oji-2016mid#3]
現状のデフォルトアイコンだと寂しいので何かあったら良いかなと。
とはいえ、言うだけだとアレなので一応私から貼っておきます。

![yapcasia8oji](https://cloud.githubusercontent.com/assets/127601/14466283/1841bd12-0111-11e6-8cb2-014a1f32f33b.png)

……まぁ、ちゃんとしたもの誰か作ってもらえたらいいなぁ！＞＜

**Comment by uzulla** [comment]
適用しました！

**Comment by uzulla** [comment]
モノクロなのでカラーのロゴがほしい

**Comment by kkotaro0111** [comment]
作るんで、必要記載事項ください。
せっかくなんでみんなでワイワイ、コンペ形式にしたい←

**Comment by uzulla** [comment]
要件としては
- Twitterなどアイコンにつかえる正方形で、48x48まで縮小して判別できるもの
- TwitterなどのTLで、識別性が高いもの
- 近年はアイコン表示時に角丸、丸へのマスクが行われる事が多いので、角丸程度では破綻しないものがよい。
- 以下が使える文字列
  - yapc::asia hachioji
  - yapc8oji
  - YA8C
  - ヤパチー
  - 「YAPC」、あるいは「YAPC::Asia」だけでは登場させないこと !Important
- アイコン内に、名前の文字は必須ではない
- 色はPerlに敬意を表して、青、紺、グレー系が想定されるが、特にコダワリはない
- テイストはモダンなほうが好ましい、たとえばサンセリフで、フラットなものなど（その方が、今後雑にあつかってもテイストミスマッチが発生しづらくて使いやすい）
- キャラ的なものは、相当クオリティが高くなければ不可
- もし可能ならば、サイトに掲載しやすいように、横長サイズへの展開ができるとなお嬉しい（が、これは必須ではない）
- 後々の利用を考えると、背景がベタではなく、抜けていると好ましい（白背景、黒背景でも違和感無く置けると好ましい、が、これは後でバリエーションでもよさそう）

なお、一応出しただけで、!Important以外は全部無視してもかまいません。

**Comment by hypermkt** [comment]
１案考えてみました。
- 色はPerlの色に合わせました
- ロゴはYapc hachiojiということもあり、[八王子の放射線通り](https://www.google.co.jp/search?q=%E5%85%AB%E7%8E%8B%E5%AD%90+%E6%94%BE%E5%B0%84%E7%B7%9A%E9%80%9A%E3%82%8A&espv=2&biw=1277&bih=657&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiJp7ys3pjNAhUjLqYKHX1eDVUQ_AUICCgD&dpr=1#imgrc=_)にある鳥居？を題材にしました
  - 鳥居がシンプル過ぎてカッコ悪い気もする・・・。
- フォントはMicrosoft Yi Baiti です。

![logo01](https://cloud.githubusercontent.com/assets/1726225/15899913/68ff211a-2dd8-11e6-826a-9aa6994e1679.png)

**Comment by uzulla** [comment]
放射線通り、コアなネタでいいなw
Twitterアイコンにするなら鳥居だけ使う感じですかね。
ちょーっと、ギリシャっぽくもある

トリイになにかぶら下げてもよいかも！

**Comment by mass10** [comment]
@hypermkt 大文字なやつも見たいです！

**Comment by hypermkt** [comment]
> Twitterアイコンにするなら鳥居だけ使う感じですかね。

ですですー 

ギリシャっぽいってのはパルテノン神殿ってことですかねｗ

> トリイになにかぶら下げてもよいかも！

ロゴ作ってる時もそれは感じてたので、`SHINAGAWA` と入れようかと思ったんですけど無理がありましたｗ 短冊とかですかねぇ〜。

> 大文字なやつも見たいです！

調整します！

**Comment by hypermkt** [comment]
@mass10 
- 同じフォントで大文字にしました。

![logo02](https://cloud.githubusercontent.com/assets/1726225/15968069/62199b30-2f65-11e6-8886-7abd6ace0c00.png)

---

別案が思い浮かんだので他のも作ってみます。

**Comment by mass10** [comment]
@hypermkt ありがとうございます！なんかメジャー感ありますね。

しかし鳥居の完成度高い。

こういうのっていろいろいじった挙句、結局最初のやつに戻ったりすることありますよね〜笑

**Comment by hypermkt** [comment]
ありがとうございますｗ 友人に聞いたらこれは[鳥居ではなく単なる入り口](http://murauchi.info/photo_hachioji_nishihoshasen_youroad_01.jpg)だそうですｗ 鳥居に見えてしまうのは日本人の心情・・・

そうですね〜、いろんなパターンを見つつもやっぱり最初が良かったと思うときはありますね。

**Comment by hypermkt** [comment]
第２案を作ってみました
- 少しやんちゃなフォントで勢いを出す。過去のyapcロゴに似たのがあったような。
- 7/2,3は八王子で七夕まつりが開催されるので、七夕の飾りをモチーフにしてみた
  - イラストは[フリー素材](http://gahag.net/008374-star-festival/)を加工しました 

![logo03 1](https://cloud.githubusercontent.com/assets/1726225/15982421/ad2d50d8-2fc1-11e6-9332-2da24010155f.png)

**Comment by uzulla** [comment]
ツイッターアイコンが〜ほしい〜

**Comment by hypermkt** [comment]
[これ](http://matome.naver.jp/odai/2142251248849318601)を参考に400x400でアイコン部を切り出しました〜

![twitter_logo1 1](https://cloud.githubusercontent.com/assets/1726225/15982382/ebdfe986-2fc0-11e6-9ac1-83ab1c5d3bae.png)

![twitter_logo2 2](https://cloud.githubusercontent.com/assets/1726225/15982381/e4b5b550-2fc0-11e6-9685-c18200017633.png)

**Comment by kkotaro0111** [comment]
![ya8c_logo](https://cloud.githubusercontent.com/assets/1256392/15988593/b35a2dfc-3091-11e6-8197-baf754c8926e.png)
![ya8c_logo_icon_1](https://cloud.githubusercontent.com/assets/1256392/15988594/bbc1aeca-3091-11e6-98ea-1ef8906cc37c.png)
![ya8c_logo_icon_3](https://cloud.githubusercontent.com/assets/1256392/15988595/befbd818-3091-11e6-80f4-494724256b70.png)
![ya8c_logo_ogp](https://cloud.githubusercontent.com/assets/1256392/15988596/c0e28528-3091-11e6-96fd-8fe14cdb6e4a.png)

俺からも1案、置いときますー

ロゴマークは、
YAPCというイベントの流れを終わらせない、という開催動機と、
楽しいことがいつまでも続くように、との願いも込めて、
メビウスの輪をモチーフに用い、
「八王子」の「８」を表現しております。

カラーは、Perlのサイトから引っ張ってきてます。

１つ目は、標準的なロゴの組み合わせ
２つ目は、ロゴマークのみ。正方形枠（アイコン向け）。
３つ目は、全要素を正方形枠に収めたもの（アイコン向け）。
４つ目は、OGPです。

**Comment by hypermkt** [comment]
めっちゃかっこいい！！！！！！

**Comment by uzulla** [comment]
うーんプロいｗ

**Comment by uzulla** [comment]
kkotaro画伯のアイコンをつかい、ばーちーアイコンはあいすべきSlackのアイコンにしました。

**Comment by hypermkt** [comment]
良いと思います！ Slackアイコンに使われてよかったｗ あざます！

**Comment by uzulla** [comment]
ロゴが無事決定したのでクローズします！ありがとうございました！

**Comment by mass10** [comment]
おお、おおおおお〜

**Comment by makamaka** [comment]
@kkotaro0111 ロゴのデータってどこかにあがってたりします？
（立ち入り禁止紙等に使用したいです）

**Comment by kkotaro0111** [comment]
gh-pagesのブランチに上がってます
必要なサイズ、ファイル形式等を言っていただければ、別途用意します

**Comment by makamaka** [comment]
ありがとうございます！　確認してみますー

**Comment by makamaka** [comment]
@kkotaro0111 
小さくして使おうとするとロゴ部分だけ表示がおかしくなってしまうのですが、イラレあまり使ってなくて対処方法がわからないです。どうしたらよいでしょう？

![2016061901](https://cloud.githubusercontent.com/assets/127601/16176190/58c6a06c-3642-11e6-9b7f-20ae23f7177a.png)

**Comment by kkotaro0111** [comment]
![ya8c_logo_edit_ai____100___rgb_ _](https://cloud.githubusercontent.com/assets/1256392/16176256/be4bd1e4-3644-11e6-93b6-7bbba8373338.png)
リサイズする、オブジェクトを選択後、変形パネルの、下部のチェックボックスを確認してください。
両方チェックがついていれば、たぶん変にはならないと思います。

**Comment by makamaka** [comment]
出来ましたー！　ありがとうございます！
