### ISSUE TITLE
インターネット担当者決める

### ISSUE THREAD

**Issue by Shinpeim** [hachiojipm/yapcasia-8oji-2016mid#30]
- [x] 主ネット担当 : ravelll 
- [x] 副ネット担当 :  masawada
- [ ] 予備ネット担当 :

**Comment by ravelll** [comment]
twitter 無いと死ぬ人です。
https://twitter.com/ravelll

**Comment by uzulla** [comment]
Twitter担当がSPOFになるとこまるので、主系と、副系統がほしいですね！
主副がきまったら公式TwitterのID/PASSはSlackのDMでおくります。

**Comment by masawada** [comment]
副ネット担当やりたいです!
http://twitter.com/masawada

**Comment by karashi39** [comment]
部屋担当に立候補していますが、人数次第ではネット担当に変更しても良いと思っています。

**Comment by uzulla** [comment]
#32 に委譲
