### ISSUE TITLE
会場諸注意

### ISSUE THREAD

**Issue by Shinpeim** [hachiojipm/yapcasia-8oji-2016mid#31]
# 会場注意
- 当日はセミナールーム＋ホワイエ以外は解放しない
- セミナールームでの飲食はOK（ただし、昼飯時以外は常識的に考えて「ご飯」はNG）
- ホワイエは迷惑がかからない範囲で飲食自由
- ゴミは全部自分でもってかえる事（ゴミ箱は利用不可能、封鎖）、ゴミも忘れ物扱いする
- 忘れ物はスタッフが控え室に確保し、ツイッターで告知
- 会場の冷蔵庫の中のものは手出し不可能（封鎖）
- 煙草は外にでて、ちょっと行く必要がある
- おとした、こぼしたはある程度自己解決しつつ、スタッフに言う
- セミナールーム内とホワイエは写真撮影OK、廊下はNG。他人の映り込みには配慮すること。トーク中（人によるが）撮影はOKだが、パシャパシャ音をだしながらの撮影はご遠慮ください（録画してるので）
- アルコールは全面不可
- 入場のQRコードは「再発行は絶対に不可能」です、一般参加、登壇者、スタッフ例外なく再発行不可能です。大事な事ですから二度いいます、再発行できません。絶対に無くしたらダメ。
- また、QRコードに記載された名前の本人以外がQRコードをつかった場合、不法な侵入としてセキュリティなどへ引き渡します。
- 「MSは例外をゆるしません」（ https://codeiq.jp/magazine/2016/04/40275/ ）
# 防災注意
- 地震のときはまず部屋から動かないように指示、ビル警備のアナウンスがあるまで移動させない。
- 火事の場合も同様にビル警備が確認して必要に応じて誘導される。やむを得ない場合は附室-1から非常階段で降りる、スタッフは誘導する。
  - 事前にフロアマップを見て、附室-1までの経路を確認すること
  - 附室-1からの再入場はできないので、非常時以外はでないこと
  - 附室-1にたどり着けない等の場合、天井に避難経路の標識はあるのでそれに従う
  - 附室-1にエレベーターはあるが、階段を使うこと
# けが人など出たら？
- とにかくリーダーにエスカレーション
- かるい外傷は応急キットをつかうなどする（ただ、絆創膏で不足なレベルは救急車）
- 意識がちゃんとして、自立歩行が難なくできるなら自身で病院にいくことを検討してもらう、頭部にかかわる系ならば、救急車を検討する
- 意識ない、あるいは自分で移動できない等は救急車を呼ぶ
  - 救急車が停車する場所の指示が別途必要なので、まずmyfinderさん、uzullaと連携する。
  - 上位がつかまらなければ電話
  - 救急車は119、住所は 〒108-0075 東京都港区港南２−１６−３ 品川グランドセントラルタワー
  - 119 にかけたことがない人はこちらを見ておく事 http://www.tama.to/ben/index/bousai/119/
- 「一応」近くの総合病院は以下
  - http://itp.ne.jp/shop/KN1301062600000005/
  - http://itp.ne.jp/shop/KN1300060500413043/
  - ただし近いとは到底言えないのでもし聞かれたら教える程度で。本人が帰宅して対応できないレベルなら救急車
## AED
- AEDを知らない人は見ておきましょう http://www.jhf.or.jp/aed/how.html

2F（エントランス）
![2016-06-06 17 36 04](https://cloud.githubusercontent.com/assets/870716/15816374/7eda9a90-2c0d-11e6-9f96-853ae0833840.png)

30F（会場から１階下）
![2016-06-06 17 35 58](https://cloud.githubusercontent.com/assets/870716/15816382/8375d844-2c0d-11e6-99df-cd0017c0a108.png)
# セミナールーム設備
- 机、マイク \* 2、ピンマイク \*  2
- プロジェクタはアスペクト比 16:9、VGAケーブル接続、VGA<->mini display port変換は運営が用意する
- 空調はスタッフが操作してよい
  - 暑い寒い等はtwitter経由で拾い上げ、部屋担当が操作
- wifi は "MSFTOPEN"が利用可能。ポートは全部開いているが、トラフィック監視はされていると自覚すること。「Microsoftのサイバー犯罪トラッキング能力はすごいぞ」
- 電源は床のものを自由に使用可能、タップはみなさん持参すること
# タスク
- [x] AEDの場所を確認 ＞ Myfinderさん
- [x] wikiに転記 https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E4%BC%9A%E5%A0%B4%E6%83%85%E5%A0%B1%E3%80%81%E8%AB%B8%E6%B3%A8%E6%84%8F
- [x] ウェブサイトに整形して設置する 
- [x] 119 番にかけた事がない人のためになんらか手順書みたいなの、住所と名前などを聞かれるので、住所(上に書いた）
- [x] 最後にしおりとして印刷して、みんなに配る #46 に委譲
- [x] 登壇者に  DisplayPort接続で、画面は16:9だと伝える #44 に委譲

**Comment by Shinpeim** [comment]
![img_1665](https://cloud.githubusercontent.com/assets/876988/15798403/e9461c3e-2a72-11e6-9da2-79fc431a4630.JPG)

会場地図

字がきたなくてすんません……

**Comment by timakin** [comment]
# ライト
- プレゼンモードがあるのでいい感じの演出をしたければそちらを利用

# wifi
- MSFTOPEN。規約同意すれば使い勝手良く利用可能。

# マイク
- マイクはピンマイクと卓上マイクの両方を使うことができます。
- 音量調整はパネル上のボタンをタップして行えます。

**Comment by Shinpeim** [comment]
ホワイエの中までは写真OK、廊下はNO撮影。クラウディアさんはOK

**Comment by timakin** [comment]
冷蔵庫は塞ぎます。繰り返しになりますが飲食は自分で持参。

**Comment by Shinpeim** [comment]
ゴミ箱も封鎖します

**Comment by Shinpeim** [comment]
アルコール、持ち込みダメです！

**Comment by timakin** [comment]
電源は下に埋まってます。なので電源とインターネットはめでたく確保です。

**Comment by Shinpeim** [comment]
１日ごとに設置、撤収を行います

**Comment by Shinpeim** [comment]
掃除用具はスタッフ側でもってくる必要あり

**Comment by Shinpeim** [comment]
忘れ物は「ゴミ」も忘れ物扱い、忘れ物アナウンスする。

**Comment by Shinpeim** [comment]
会場は飲食OK

**Comment by Shinpeim** [comment]
タバコは外で吸ってもらう

**Comment by hypermkt** [comment]
まとめありがとうございます！

**Comment by uzulla** [comment]
AED追加した

**Comment by myfinder** [comment]
119に言う住所はあれでいいんですが、救急車自体は車寄せにつけてもらう必要があるのと、そこからの案内は私とスタッフでの対応となります。

**Comment by myfinder** [comment]
なので、31Fって言うよりも、「港区港南２−１６−３ 品川グランドセントラルタワー」とだけ言ってくださればと。

**Comment by uzulla** [comment]
了解です、そのように修正しました。

**Comment by uzulla** [comment]
http://yapcasia8oji-2016mid.hachiojipm.org/venue_info/
に転記した

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E4%BC%9A%E5%A0%B4%E6%83%85%E5%A0%B1%E3%80%81%E8%AB%B8%E6%B3%A8%E6%84%8F
Wikiに転記したのでClose
