### ISSUE TITLE
スタッフ担当箇所リスト

### ISSUE THREAD

**Issue by Shinpeim** [hachiojipm/yapcasia-8oji-2016mid#32]
# 全体タイムテーブル

スタッフのタイムテーブルの管理をgoogle docsに移しました。
趣旨は「何時、誰が、何の役割をしている(はず)」を見えるようにするものです。

https://docs.google.com/spreadsheets/d/1QlwF2rwvY9-TOn9IyGgq_LLsDSYCPviAkTpBZWxM8uM/edit?usp=sharing

当日はmyfinderさんに印刷してもらった物をスタッフルームに貼って貰います。
誰がいつ頃抜けるか等の参考として下さい。
# 休憩時間

休憩時間等何かあれば表にコメントを付けるかissueに書いておくと事前調整がスムーズかと思います。
あくまで担当者間の調整ツールとして使ってくださいというスタンスで「ここに書いたから絶対守らなければならない」という意味では無いです。
最終的には各部屋、受付、ネット、カメラ、遊撃の担当間で時間を融通しながら休憩してください。
# 古い情報

tontonは閉鎖(過去の参照として ttp://tonton.amaneku.com/list.php?id=20160610182539_fCzjm9 )

**Comment by Shinpeim** [comment]
![image](https://cloud.githubusercontent.com/assets/876988/15798476/e86a5c6a-2a74-11e6-9c20-83d7338c7db7.png)

**Comment by Shinpeim** [comment]
![image](https://cloud.githubusercontent.com/assets/876988/15798483/202ed914-2a75-11e6-98a5-d54ff85ed7f7.png)

**Comment by hypermkt** [comment]
- 氏名：千葉　誠（ちば まこと）
- ニックネーム：バーチー
- ![hypermkt](https://cloud.githubusercontent.com/assets/1726225/15798567/4ad5c7d4-2a77-11e6-8322-79b61ea08ba3.jpg)

**Comment by kkotaro0111** [comment]
- 氏名：川嶋　光太郎（かわしま　こうたろう）
- ニックネーム：kkotaro
- <img src="https://cloud.githubusercontent.com/assets/1256392/15799353/9f024c02-2a94-11e6-9379-5be2033f8977.jpg" width="140" height="140">

**Comment by uzulla** [comment]
#25 よりコピペ 

```
お部屋リーダー

kkotaro0111
karashi39
hasegawatomoki
hypermkt
shinpei0213
timakin
pocket7878
motchang
```

**Comment by hypermkt** [comment]
ウル覚えですが部屋リーダーの電話番号は共有が必要というお話ありませんでしたっけ？共有が必要な場合は 公開issueで電話番号を記載するのは好ましくないので、 #priv_staffで共有しますか？

**Comment by hypermkt** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/34#issuecomment-223765414 に書いてありましたね。電話番号は必要。

**Comment by motchang** [comment]
- 氏名
  - 岡本浩治（おかもと こうじ）
- id
  - @motchang (もっちゃん）
- 写真
  - ![2016-06-04 17 26 52](https://cloud.githubusercontent.com/assets/1159316/15803497/b2e9900e-2b1b-11e6-80be-2e4c2dfb7f10.jpg)

こんなんでよろしいでしょうか

**Comment by timakin** [comment]
- 氏名
  - 高橋誠二
- id
  - timakin / @**timakin**
- 写真
  - ![11988627_904292039650525_6320331555141793918_n](https://cloud.githubusercontent.com/assets/2871985/15804577/ad90a214-2b48-11e6-957d-26cc0d2173e1.jpg)

**Comment by uzulla** [comment]
何部屋をやりたいかみんないっておくれ、ABCで、Cが一番ひろくて、Aが次にひろくて、Bが一番狭い。

特に希望がなければ僕が勝手にアサインするよー。

**Comment by Shinpeim** [comment]
とくにないです！

**Comment by kkotaro0111** [comment]
カメラレンタル＋録画担当ということもあり、俺のカメラが配置される部屋の担当だと、対応しやすさもあって嬉しいです。

**Comment by kkotaro0111** [comment]
#39 をみると、サブリーダーはトーク中の移動ができない。
写真の副担にもなってることを考えると、部屋リーダーである必要がありそう。
ただ、この2者は交代可能らしい。
タイムキーバー側になったときの撮影はどうすればいいか。

**Comment by kkotaro0111** [comment]
ん？ #39 では、ツーマンセルだけど、
ここのリスト見ると、2交代制ツーマンセルだ。
タイムキーパーは主と副とで交代すれば良い？

**Comment by uzulla** [comment]
@kkotaro0111 
前提として、部屋にスタッフが２人以上常時存在が必須要件です。
（緊急トイレなどは予備役を呼び出しつつ交代すれば、よいとして）

ツーマンセルは２人一組という意味で、当然交代の必要があるのでそれが２組になります。
なので、１部屋に主/副で4人が割り当てられます。

**Comment by karashi39** [comment]
部屋リーダーに立候補したものです。

氏名 : 佐藤将道（さとう まさみち）
id : karashi39 (からし）
写真 : 
![image](https://cloud.githubusercontent.com/assets/12491692/15822171/2bf243b0-2c2f-11e6-8295-434a9f5beb80.png)

役職に希望はありません。どんな仕事でも楽しみます。

**Comment by hasegawa-tomoki** [comment]
部屋リーダーやりますー
どこでも良ければA部屋がいいな！

氏名: 長谷川智希 （はせがわ ともき）
id: GitHub: hasegawa-tomoki / Twitter: tomzoh / Slack: hasegawatomoki
写真:
![p8244421](https://cloud.githubusercontent.com/assets/3850359/15982496/2e1017ec-2fc4-11e6-91ff-ebdc41c0cca7.JPG)

**Comment by pocket7878** [comment]
部屋リーダーに立候補してました！

氏名: 十亀 眞怜(そがめ まさと)
ID: Pocket7878
写真:
![9ba2deb2-b836-43b2-bb78-b3e582ce532f](https://cloud.githubusercontent.com/assets/236528/15983076/ee2afba2-2fd6-11e6-9de8-b2885bdc8e88.JPG)
しまった写真横向きだ...

**Comment by mass10** [comment]
遊撃でお願い致します

**Comment by uzulla** [comment]
@mass10 タイムキーパーはむずかしく、遊撃でないとダメということでしょうか？

**Comment by mass10** [comment]
@uzulla いいえ。自分がいない、と勘違いしました。タイムキーパーします。

**Comment by hkoba** [comment]
（まかまかさんに勧められたので）遊撃立候補します～

**Comment by uzulla** [comment]
できれば部屋担当になっとくれ〜

**Comment by hkoba** [comment]
おっす！部屋担当、了解です！

**Comment by isuka** [comment]
slackは流れるので、一応こっちにも貼っておきます。
[全体タイムテーブル](https://docs.google.com/spreadsheets/d/1QlwF2rwvY9-TOn9IyGgq_LLsDSYCPviAkTpBZWxM8uM/edit?usp=sharing)

**Comment by mass10** [comment]
みんな“●”とかを入勝手にれていく感じでしょうか

**Comment by mass10** [comment]
勝手に入れてく

**Comment by isuka** [comment]
とりあえずコメント貰うかissueが更新されたら反映していくつもりですが、
googleアカウント無い人いたらどうするかは未定です。(どの程度そういう人がいるのか分からないですが)

**Comment by isuka** [comment]
スタッフのタイムテーブルをgoogle docsに移しました。
未割当の役割(各部屋の3人目等)で希望があればdocsにコメント付けるかissueに書いてください。

**Comment by mass10** [comment]
スマホで見るにはちょっと重いかしら

**Comment by isuka** [comment]
@mass10  何か軽くする良い方法ありますか？

**Comment by uzulla** [comment]
HTMLに書き出すとかしたらいいんじゃないですかね。

HTMLになってれば、公式サイトのどっかにおいちゃってもいいですよ。

**Comment by mass10** [comment]
@isuka いえ、この表現力を保ったままでは難しいでしょう。

この表は重要だと思っているのですが、当日スマホで見るようなシーンが本当にあるのか、ってとこですね。

各担当は自分の居場所さえわかっていれば(当日は)見ないのかな...

**Comment by myfinder** [comment]
各位が持ち場で見ることはないと思うのですが、スタッフ控え室として確保してある部屋に貼りだしておきましょう。"〇〇さん、今日どこで抜けるのかな" 的なの含め、全体的な動きを一望できるものはあったほうが良いと思いますので。

@isuka A3位のサイズなら用意できるので、当日の朝もしくは7/1(前日)に書き出しておきますよ。

**Comment by uzulla** [comment]
そろそろConnpassとの突き合わせもしないといけないんですが、
ハンドル名が統一されてないのでこの表に入力してもらえるとたすかるなあ、という気分になっております。

**Comment by pudding666** [comment]
2日目のインターネット担当を希望します。朝から参加です。
休憩時間が決まっている必要はないので、適宜で取れたらと思います。

**Comment by isuka** [comment]
Room A〜CのT.K.2が各1名、計3名空いてます。
役割が決まっていない人で我こそはという人はタイムテーブルにコメント付けるか、レスをお願いします。
あと、聞きたいトークある人は該当の時間帯に同じくコメント付けておいてもらえると　調整がスムーズかと思います。

**Comment by mass10** [comment]
(もし覚えていたらフリクションペンを持って行こう...)

**Comment by isuka** [comment]
全員アサインが終わりましたが、調整が必要です。
Room A TK、Room C TK2に移れる(移っても良い)方はいらっしゃいませんか？

**Comment by acchanAlexander** [comment]
いま何にもアサインされていなくて、
ルームCのタイムキーパーに立候補しますー！

**Comment by uzulla** [comment]
@isuka さんよろしくおねがいします！
(ついででもうしわけないんですけど、「プロジェクタ&マイクのシステム立ち上げ（とテスト）」は早めにやってしまいたいので、9:00くらいに移動しておいてもらえるとたすかります。）

**Comment by isuka** [comment]
@acchanAlexander @uzulla
タイムテーブル反映しました。

**Comment by keima** [comment]
@isuka 
13:30に受付を縮退するときに、最低でも3名は開放予定でございます。

**Comment by isuka** [comment]
@keima
誰が抜けるかは状況次第だと思いますが、とりあえず13:30に最低3名遊撃へ編入の件反映しました。
Room AのTKが一人足りない状況なのですが、縮退した受付の人(遊撃でも良いかもしれませんが)がそのまま部屋担当にコンバートって調整可能でしょうか？

**Comment by kysnm** [comment]
ん、横からすみません。受付としては人員を渡す事は出来ると思います。その方々をどこに配置するかを決める担当者というのは決まっているのでしょうか？要するに「調整可能でしょうか？」というのは誰に対しての問いかけかつかみかねています :sweat_drops: すみませんが、上記の発言をもう少し噛み砕いて言っていただけないでしょうか

**Comment by isuka** [comment]
言葉足らずですみません。
最終チェックはuzullaさんになると思いますが、タイムテーブルの管理と調整は私がやっているので、配置を決める担当者としてはひとまず私で良いかと思ってます。

「調整可能か？」という質問は、「遊撃へ編入じゃなくて部屋担当へ回るよう解放者に言ってもらえますか」という意味と「タイムキーパーやりたい(or やれる)人を解放してもらえますか？」という意味でした。分かりにくくてすみません。

最低3人解放との事なので、遊撃2名+受付1名とすると、必然的に解放者がそのまま部屋担当になると思っています。
受付の人が縮退時に部屋担当に回る前提で書いているので、前提が違ったらすみません。

**Comment by uzulla** [comment]
だれが受付からコンバートとなるかについては当日適当に声掛けします。
（あんまり見知った方がいないし、立候補はいただけなかったので、つかみかねている）

ただ、おひとりacchanAlexanderさんがはいってくれたので、あと一人だ〜となっております。

**Comment by kysnm** [comment]
ありがとうございます
理解しました

> 誰が抜けるかは状況次第だと思いますが

という言葉通りの状況なので、そういう風に調整してもらえると助かるという意味で認識しました

**Comment by kysnm** [comment]
というわけで横取りしちゃってごめんなさい
@keima san

**Comment by keima** [comment]
@kysnm いえいえ、むしろ助かります m(_ _)m

**Comment by uzulla** [comment]
とりあえず、A部屋のTKがいないのはもう埋めようがないので（進展しようがないので）、このISSUEはクローズしてよいかなとおもいますがどうですか @isuka 

（A部屋の副チームのTKを受付からひっぱるのは別ISSUEを立てます）

**Comment by isuka** [comment]
@uzulla
はい。クローズで良いと思います。
タイムテーブルも更新しました。
