### ISSUE TITLE
受付担当者を決める

### ISSUE THREAD

**Issue by Shinpeim** [hachiojipm/yapcasia-8oji-2016mid#33]
- [ ] 人を決める
  - [ ] 主エントランスリーダー：
  - [ ] 主エントランスサブリーダー：
  - [ ] 副エントランスリーダー：
  - [ ] 副エントランスサブリーダー：

**Comment by Shinpeim** [comment]
![image](https://cloud.githubusercontent.com/assets/876988/15798491/6f8ebf7e-2a75-11e6-8d33-7b0a4f809e68.png)

**Comment by uzulla** [comment]
#25 よりコピペ

```
konnkonn
takakiku810
62jun26
wata727
makamaka
```

**Comment by makamaka** [comment]
makamaka が抜けておる！

**Comment by myfinder** [comment]
当日の入館証運用はslackチャットで相談しますが、スタッフミーティングのような形でやることを基本的に想定しているということだけは今日のうちに書いておきます。

**Comment by uzulla** [comment]
「しおり」をつくりますが、朝一回でmtgしませう。

**Comment by uzulla** [comment]
#32 に委譲
