### ISSUE TITLE
スタッフ緊急連絡網（電話）

### ISSUE THREAD

**Issue by Shinpeim** [hachiojipm/yapcasia-8oji-2016mid#34]
- [ ] 全リーダーのTEL番号をuzullaにあつめる
- [ ] コアスタッフ＆ネット担当にシェアする

---
- [ ] ルーム内での連絡はslackで、必要と判断したらルーム内で個別に連絡先を交換ください

---
- [ ] uzullaのTEL番号はのちほどスタッフ全員に公開します。

**Comment by timakin** [comment]
アプリ導入等でつまづいてた面もあるのでLINEでいきましょうと言う話になった（気がしますが間違いだったらすみません）

**Comment by uzulla** [comment]
まあ、クリティカルな事は電話でやりましょう、ということで連絡網を作りましょう。
ここにTEL番号かけないので、priv_staffなどでとりまとめて紙などにする

**Comment by myfinder** [comment]
@Shinpeim そのURLを晒されたら困る＞＜けどLINEでやるってことになったのでもういいです。。。

**Comment by uzulla** [comment]
🙇 

部屋リーダー確定したら、収集しましょう。

**Comment by Shinpeim** [comment]
あっ！すみません……！アホでした

**Comment by uzulla** [comment]
こちら、扱いがむずかしすぎるので愚直な方法にします。
私が各リーダーに直接きき、私とコアスタッフ（myfinderさん、makamakaさん）と、ハブになるネット担当者だけにシェアしようとおもいます。（8人くらいなら、DMで全部できるやろ）

各ルーム（や受付）の範囲での個人間通信は基本Slackでやってもらい、
もし各ルームの中で必要そうなら、各部屋の中で閉じた形で当日朝に個別共有してもらうことにします。

**Comment by uzulla** [comment]
しおりにかきます、ということでClose。
