### ISSUE TITLE
スタッフ識別章を考える

### ISSUE THREAD

**Issue by hasegawa-tomoki** [hachiojipm/yapcasia-8oji-2016mid#35]
スタッフ識別章を考えよう。
腕章とか。

**Comment by silfsquare** [comment]
思い出しましたが、首から下げるIDカードホルダーがうちに30枚くらいあると思います！

**Comment by hasegawa-tomoki** [comment]
あざます！
一般参加者用の名札も検討したく、良き時に写真みせてください！

**Comment by uzulla** [comment]
http://www.amazon.co.jp/dp/B004ORZ3CA

これで、一般透明（200個）、スタッフ赤（50個）、トーカー青（100個）とかにしますかねー。
トーカーと一般を別ける必要はないかな。

中に入れる紙はこれかな

http://www.amazon.co.jp/dp/B0018HHRYG

あとはマジック一式か、予算1万あれば足りそう。

**Comment by uzulla** [comment]
コンパスの受付表印刷してきてもらえば、色々平和な気はしてきた
![_2016_06_05_6_30](https://cloud.githubusercontent.com/assets/870716/15802247/1348f528-2ae7-11e6-9c14-3fd38c0f31a5.png)

**Comment by hasegawa-tomoki** [comment]
ああ、自分が見てたのもこの価格帯でした。
言い出しっぺとして自分やります。
やっぱち、ロゴとかあるんでしたっけ。
あるなら隅っこに（自宅で）印刷して持っていきたい。

**Comment by hasegawa-tomoki** [comment]
（Issueみつけた。ごめんなさい。8ロゴ。）

**Comment by uzulla** [comment]
ロゴほしいですね、無いです

**Comment by uzulla** [comment]
@hasegawa-tomoki 
一点だけ、最終的になんか買う事になったら買うんで、いってちょうだい！

**Comment by hasegawa-tomoki** [comment]
了解！
中に入れる紙は長谷川が自宅のプリンタでロゴを印刷できる様なのを探す予定。
来週ぐらいに買えればいいですね。
うずらさんに買ってもらってもポケットマネーですよね？
自分が欲しいモノなので自分買いまっす！

**Comment by uzulla** [comment]
@hasegawa-tomoki 
そうか、はせがわさんは他のカンファレンスオーナーでしたねｗ
でもまあとにかく買う前に一声ください。

**Comment by hasegawa-tomoki** [comment]
ロゴ決まったら、中に入れる紙を決め、名札ホルダーも決まるのでご報告します！

**Comment by hasegawa-tomoki** [comment]
名札は @uzulla さんが見つけてくれた以下が最安ぽい。
https://www.amazon.co.jp/dp/B004ORZ3CA
中にこのカードを入れて
https://www.amazon.co.jp/dp/B0000ACBTA
以下のような印刷をするのでいかがでしょう。
印刷は長谷川のプリンタでやるので経費不要。

![-51275-crop](https://cloud.githubusercontent.com/assets/3850359/15988387/aa492f22-3089-11e6-9833-99e1d6ef22f0.png)

ロゴ、横長のを作って頂けると、書くエリアを広くできます。

**Comment by uzulla** [comment]
おつです！では買いますが、amazonからhasegawaさんの所にamazon直送便すればよいですかね？（DMで住所もらえるとたすかります）

ロゴに関しては、まあ現行の物で十分ではないでしょうか。

**Comment by hasegawa-tomoki** [comment]
あざます。
送っておきます。

買って頂いても良いですし、こちらで買っても良いですよ～！

**Comment by uzulla** [comment]
名入れ、赤いやつ50、透明400（二日来る人が多いので）、名刺サイズの紙100シート（1000枚）分。
あと、サインペン10本を、はせがわさんところに直通注文Done。

**Comment by hasegawa-tomoki** [comment]
届いた & 検品完了。
週末にでも印刷しとく。

**Comment by uzulla** [comment]
あ、届いたものについてるAmazon納品書について持ってきてください、お手数ですがお願いします。

**Comment by hasegawa-tomoki** [comment]
Okay

名札の印刷、こんな感じでするつもり。
レビューお願いシマス。

チェックポイントとしては:
- 名札の表示は以下でOK？（飛び入りはATENDEEにする？）
  - 「レギュラートーク登壇者」「LT枠」「「俺は絶対に当日飛び入りトークするんだ」枠」 → SPEAKER
  - 「スタッフ枠」 → STAFF
  - 「一般参加者枠」「「遠方だから絶対決まってないと死ぬ」枠」 → ATENDEE
- 印刷数量はこんなんでOK？（= 余分はこれでいいよね）
  - STAFF 80 → 100枚印刷
  - SPEAKER 107 → 150枚印刷
  - ATENDEE 300 → 350枚印刷

詳細:
https://docs.google.com/spreadsheets/d/1y62rX4ueX65YkCkhdZbzlGPDj0zo_PXNPo3t_3NK8eY/edit#gid=0

**Comment by uzulla** [comment]
「スタッフ（STAFF）」と「それ以外（無印）」でよいです。むしろ受付でしらべて渡すのは大変なので同じにしてください。

枚数については、スタッフ100枚、普通500枚のそれでOKです！

あとは一応印刷イメージをシェアしてもらえるとすごくうれしい！

**Comment by uzulla** [comment]
あ、イメージ上にあったね、すいません、ちゃんとチェックできてませんで。
STAFFはこれでもちろんOKで、ほかは無印(テキスト無し)でよいです。
あるいは「参加者」というのの良い英語を私はしらないｗ

**Comment by myfinder** [comment]
送り先、弊社着の方が都合がいいものがあれば私が承っておきますよ。

**Comment by hasegawa-tomoki** [comment]
了解デース。
スタッフはこれで、それ以外無印で、100枚、500枚で作りマッス。

@myfinder さん:
名札印刷したら宅配でお送りしても良いですか？
良ければ送り先教えてください～！

**Comment by kysnm** [comment]
「それ以外（無印）」って受付で配る想定なんでしょうか？経験上安い名札入れって紐が絡まって扱いがツラいんですよね。専任の人が欲しいかも。あと記入するスペースってどこになるのでしょう？受付は机を出せないのでその辺が気になりました

**Comment by myfinder** [comment]
@hasegawa-tomoki slackで返信しておきました。

**Comment by uzulla** [comment]
@kysnm （スタッフ以外は）名札はかってにとってけ、ほしくない人はもってかなくていいぞ。でいいです。

配る場所は、受付でなくてもよいので、B部屋前の机にでもおいとこうとおもいます。
（まあ、スタッフは「一目でスタッフとわかる」ために名札に価値はありますが、それ以外はコミュニケーションツール的なオマケです）

**Comment by myfinder** [comment]
31Fにそういうのを受け渡す机を出すことは可能です。なので、2Fでは最低限入館証の引き渡しのみをして、31F側で残りを吸収するという手もありです。

**Comment by uzulla** [comment]
@hasegawa-tomoki 宅急便の領収書とっておいてください〜

**Comment by uzulla** [comment]
ISSUEに経緯がかいてなかったので、書いておくと…。

１回目の打ち合わせで
私）名札別になくていいじゃない？スタッフ識別表はなんかあってもいいけど
はせがわさん他）あったほうがいい
はせがわさん）私がやる！
私）じゃあおねがいします！

という経緯があり、主催的にはスタッフ識別表だけはほしいので、そこはスタッフに手でくばります。

ただ、普通の参加者表は（私は）特になくてよくて、受付の負荷にはしません。ほしい人がいるのは把握したので、適当にくばりましょう。

とにかくはせがわさん（とロゴ制作のkkotaro）ありがとう！！

というのが（私からみている）経緯です。

**Comment by kysnm** [comment]
@uzulla cc: @myfinder 31F 配布であればありがたいですー。先述の通りヒモがからまる事が想定されるので、遊撃の方にたまに見てもらえると良いかと思います

**Comment by hasegawa-tomoki** [comment]
@uzulla 了解ッス。でも、言い出しっぺが手で持っていく手間を省くだけなので気にしないで。

**Comment by uzulla** [comment]
@hasegawa-tomoki 
お忙しい所もうしわけないのですが、進捗どうでしょう！

**Comment by hasegawa-tomoki** [comment]
すみません、こちらで報告していなかった。
先週末（昨日）印刷を終えて、本日朝に @myfinder さんに向けて発送しました！ :+1:

**Comment by myfinder** [comment]
個別にご連絡はいただいております。

**Comment by uzulla** [comment]
:bow:

**Comment by myfinder** [comment]
@hasegawa-tomoki 先ほど受け取りました。

**Comment by uzulla** [comment]
👍

**Comment by uzulla** [comment]
@myfinder すごい適当でいいんで、内容物をシャメしてもらえるとうれしいです。(本当の確認は前日やるとして)

**Comment by myfinder** [comment]
![wp_20160628_12_30_13_rich](https://cloud.githubusercontent.com/assets/74346/16403109/dcf89d54-3d2c-11e6-883e-ed0423a38e81.jpg)

**Comment by myfinder** [comment]
@uzulla ↑の通りです。

**Comment by uzulla** [comment]
よさそう！とりあえずこれでOKということでクローズしますね！
