### ISSUE TITLE
飛び入りトラック

### ISSUE THREAD

**Issue by Shinpeim** [hachiojipm/yapcasia-8oji-2016mid#36]
# 情報
- Room D
- 2日および3日の10:00〜16:30
  # 必要なこと
- [x] 場所確保
- [x] トラック確保
- [x] 録画、写真はどうする？
- [x] スタッフ確保
  - [x] リーダー：しんぺい
  - [x] 副リーダー：たっくん
  - [x] サブ：tsucchi
  - [x] 副サブ：i.nozomi（3日はさらにatsukoseki）
  - [x] 溢れたひと対策：安曇さん（紙製）
  - [x] 溢れたひと対策：安曇さん（紙製）
- [x] 導線確保
# 必要なモノ
- [x] ホワイトボード（タイムテーブル用）
- [x] プロジェクタ
- [x] Macのしっぽ(morizoooさん)
# トーク受付の仕方
- トークしたいひとにはスタッフに声をかけてもらいます。
- 何時から何分間どんなトークをしたいのか聞き込み
- https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable にissueを立ててもらう
  - ちゃんとフォーマットを守ってね！
  - githubアカウントないひとの場合は代理で立ててあげても良いです
- トークの合間にホワイトボードを埋める
- ネット担当にslack経由で「新しいトーク埋まったんで宣伝してください」お願いする
# スタッフお仕事
## リーダー・副リーダー
#39 のルーム監視員お仕事 + トーク受付
## サブ
#39 のタイムキーパーのお仕事

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/85
これ、アンカンファレンス向きだよね。

やるとしたら、人とカメラとかどうしようかな…。

**Comment by Shinpeim** [comment]
@uzulla  アンカンファレンストラック、二日目の午後開始時から閉会式20分前まで時間がほしいです。

**Comment by uzulla** [comment]
それはOKです。
アンカンファレンスの（そうぞうじょうの）タイムテーブルと、必要なヒト・モノを適当にきって、みせてください。
ビデオカメラは広角のやつがあるので、それを用意します。

**Comment by Shinpeim** [comment]
@uzulla issueの内容をupdateしたので、内容確認してもらってもいいでしょうか。アンカンファレンスといってもディスカッションにフォーカスするというよりはLTソンのもう少しタイムテーブルきちんと組んだ版、という趣です。

**Comment by uzulla** [comment]
上にもかいたけど、ビデオカメラは私が（広角気味だけど）もっているので、それを貸します。
ビデオカメラスレにかいておいてください（で、ここはチェックOKでいいとおもいます）。

「最初に10分の説明」というのは、どこで誰に対してやるはなしですかね？
その４トラック部屋でなら、部屋に最初から大勢がいないとおもいますので、それが重要な事にしてしまうとまずいのでは。
（勿論それはそれでやっていいんだけど、どっかに記事として掲載しておかないと、途中参加の人はわからないのでは？）
出入りをすることをかんがえれば、「説明」がいらないような工夫（事前に周知させるとか）があったほうがよいとおもいます。

「毎日のあたまのOPで説明する」という意味だと、三つ部屋があるから10分づつはむずかしいのでは）

あと、導線（どうやって人をそちらに誘引するか、事前の宣伝含む）ですね。

**Comment by Shinpeim** [comment]
なるほどたしかに最初の説明に関してもうすこし詰めます

**Comment by uzulla** [comment]
#27 でフロアマップつくってもらってるんで、お部屋をはやめにきめたいですね！

**Comment by Shinpeim** [comment]
部屋確定しました。

フロアマップで見たところの  31C-13 です。

**Comment by mass10** [comment]
アンカンファレンスぽいのたのしそう！！

**Comment by uzulla** [comment]
スタッフ勧誘の進捗どうですか。
もう普通の人をアサインしてもよい？

このトラックはスタッフがやることが多くなるとおもうので、副チームリーダーに説明とか、こうするんだ、みたいなのをおしえないとまわらないと思うので、はやめに副チームリーダーを確保したほうがいいのでは。

「主リーダーシンペイ、副リーダーがたっくんさんで、スタッフは普通の人でもどうにかなるぞ！」と思って良いの？

**Comment by Shinpeim** [comment]
すみませんissueの変更漏れてました。

わたし含めて5人ほど飛び入りトラックのスタッフをやってくださるひとがいたので、これで回せるかと思います。

各スタッフ全員わたしは顔見知りですので、のちほどしおりを作成して渡します。

よろしくおねがいします。

**Comment by isuka** [comment]
@Shinpeim 今4名書いてありますが、もう1名はどなたでしょうか？(紙の人？)

**Comment by uzulla** [comment]
多少は事前に声掛けの仕込みをしておいたほうがいいかなっておもってて、yokuさんとsoudaiさんあたりにはこえかけてもいいんじゃないですかね。

https://twitter.com/uzulla/status/739836156041269252

あと、cakephperさんとか

https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/69#issuecomment-226145286

**Comment by uzulla** [comment]
あと、「絶対話すぞ枠」の人も、（はちぴースラックとかで）声掛けして塩梅をきいてみるとか。

**Comment by Shinpeim** [comment]
@isuka 

descriptionにも書きましたが、atsukosekiさんが3日のみ手伝ってくれます

**Comment by Shinpeim** [comment]
たしかに仕込みある程度しておいたほうがよさそうなので声かけてみます！

**Comment by isuka** [comment]
了解です。タイムテーブルに反映しました。

**Comment by uzulla** [comment]
こちら、全部の足並みがそろった感じですかね？あとはしおり？

**Comment by Shinpeim** [comment]
全部足並み揃ったと思っていただいて大丈夫です！

しおりはこのissueのdescriptionでいいかなと思っています

**Comment by uzulla** [comment]
了解です！よろしければCloseしておいてください！
（もしよろしければ、Wikiに転記してもらえるとベリーハッピーです

**Comment by uzulla** [comment]
@Shinpeim ping

**Comment by Shinpeim** [comment]
ごめんなさい通知見逃してました。本日やります！
