### ISSUE TITLE
「スタッフのしおり」をつくる

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#38]
（全部Wikiにかいたので、緊急時情報と、連絡先などにしぼったものを配布します）

**Comment by mass10** [comment]
これって紙で出してポッケにいれておきたいイメージですよね...

**Comment by uzulla** [comment]
そうですね、これは紙でだしておきます。

**Comment by uzulla** [comment]
来週くらいにWikiに全部よせたら、心優しい人が良い感じに適当に並べて印刷してくれないかなー！！（チラッチラッ

**Comment by hasegawa-tomoki** [comment]
あ。そうか。うちにある名札で良ければ印刷するよ。
ちょっと小さすぎるかな？

**Comment by mass10** [comment]
# ヤパチースタッフのしおりのイメージ

※本物は Word っぽいやつで4つ折向けに書き直すべし

2016年07月01日
2016年07月02日
日本マイクロソフト本社 品川
港区港南２−１６−３ 品川グランドセントラルタワー

<br>
<br>
<br>

![image](https://cloud.githubusercontent.com/assets/2055840/16168751/a39124cc-354e-11e6-9fcd-fba494362a10.png)
yapcasia8oji-2016mid.hachiojipm.org

---

# 連絡帳

| 氏名 | GitHub(↓) | 役割 | 電話番号 | コメント |
| --- | --- | --- | --- | --- |
| XXXXX | atsukoseki | XXXXX | 999 9999 9999 | コメント |
| XXXXX | hasegawa-tomoki | XXXXX | 999 9999 9999 | コメント |
| XXXXX | hirokita10 | XXXXX | 999 9999 9999 | コメント |
| XXXXX | hkoba | XXXXX | 999 9999 9999 | コメント |
| XXXXX | hypermkt | XXXXX | 999 9999 9999 | コメント |
| XXXXX | ichisemasashi | XXXXX | 999 9999 9999 | コメント |
| XXXXX | ikosin | XXXXX | 999 9999 9999 | コメント |
| XXXXX | isuka | XXXXX | 999 9999 9999 | コメント |
| XXXXX | karashi39 | XXXXX | 999 9999 9999 | コメント |
| XXXXX | keima | XXXXX | 999 9999 9999 | コメント |
| XXXXX | kikumoto | XXXXX | 999 9999 9999 | コメント |
| XXXXX | kkotaro0111 | XXXXX | 999 9999 9999 | コメント |
| XXXXX | kochizufan | XXXXX | 999 9999 9999 | コメント |
| XXXXX | konnkonn | XXXXX | 999 9999 9999 | コメント |
| XXXXX | kysnm | XXXXX | 999 9999 9999 | コメント |
| XXXXX | mahoyaya | XXXXX | 999 9999 9999 | コメント |
| XXXXX | masawada | XXXXX | 999 9999 9999 | コメント |
| XXXXX | mass10 | XXXXX | 999 9999 9999 | コメント |
| XXXXX | morizooo | XXXXX | 999 9999 9999 | コメント |
| XXXXX | moshisora | XXXXX | 999 9999 9999 | コメント |
| XXXXX | motchang | XXXXX | 999 9999 9999 | コメント |
| XXXXX | nagayama | XXXXX | 999 9999 9999 | コメント |
| XXXXX | nozomi-I | XXXXX | 999 9999 9999 | コメント |
| XXXXX | papix | XXXXX | 999 9999 9999 | コメント |
| XXXXX | pastak | XXXXX | 999 9999 9999 | コメント |
| XXXXX | pocket7878 | XXXXX | 999 9999 9999 | コメント |
| XXXXX | ravelll | XXXXX | 999 9999 9999 | コメント |
| XXXXX | Shinpeim | XXXXX | 999 9999 9999 | コメント |
| XXXXX | silfsquare | XXXXX | 999 9999 9999 | コメント |
| XXXXX | souhei | XXXXX | 999 9999 9999 | コメント |
| XXXXX | stefafafan | XXXXX | 999 9999 9999 | コメント |
| XXXXX | TakashiKaga | XXXXX | 999 9999 9999 | コメント |
| XXXXX | timakin | XXXXX | 999 9999 9999 | コメント |
| XXXXX | tsucchi | XXXXX | 999 9999 9999 | コメント |
| XXXXX | uzulla | XXXXX | 999 9999 9999 | コメント |
| XXXXX | wata727 | XXXXX | 999 9999 9999 | コメント |
| XXXXX | waterlow | XXXXX | 999 9999 9999 | コメント |
- 何かでグルーピングすべきか否か

---

# フロアマップ

![image](https://cloud.githubusercontent.com/assets/2055840/16168758/1c4ed468-354f-11e6-9419-3a7866021e8f.png)

<br>
<br>
<br>

---

# 災害時対応マニュアル
- 地震のときはまず部屋から動かないように指示、ビル警備のアナウンスがあるまで移動させない。
- 火事の場合も同様にビル警備が確認して必要に応じて誘導される。やむを得ない場合は附室-1から非常階段で降りる、スタッフは誘導する。<br>
  - 事前にフロアマップを見て、附室-1までの経路を確認すること。
  - 附室-1からの再入場はできないので、非常時以外はでないこと。
  - 附室-1にたどり着けない等の場合、天井に避難経路の標識はあるのでそれに従う。
  - 附室-1にエレベーターはあるが、階段を使うこと。

<br>
<br>
<br>
<br>
<br>

---

# 様々な心得

##### xxx について

##### yyy について

<br>
<br>
<br>

---

# その他メモ
- なんかいる?

<br>
<br>
<br>
<br>

---
- うちに帰るまでがヤパチーです。
- 特に状況が変わらなければ2017年もヤパチーは開催されます。また来年もご協力お願いします。

<br>
<br>
<br>

**Comment by hasegawa-tomoki** [comment]
なるほどこのサイズか。
そしたらA4に印刷するか。
プリンタあるんで出来ますよ。

**Comment by uzulla** [comment]
Wikiで！！！

**Comment by mass10** [comment]
ウッ

**Comment by isuka** [comment]
ちょっと作ってみましたけど、こんな感じですか？
両面印刷して真ん中で折る感じです。(それを半分に折れば四つ折りって事でいいかな？)
[スタッフガイド](https://docs.google.com/document/d/1BLZCvtED4SR9VZkvwjQWfXjc6M5sQZbFBuWHEs3Q3iI/edit?usp=sharing)

**Comment by mass10** [comment]
おっと、404 です～

**Comment by mass10** [comment]
おっと、ウソです～

**Comment by mass10** [comment]
4つに折れば過去の YAPC とかの名前ホルダーに収まりそうな感じですね～

**Comment by isuka** [comment]
すいません、リンクの貼り方間違えてました。
