### ISSUE TITLE
部屋担当心得

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#39]
# チームについて
- 部屋リーダー
- タイムキーパー（司会）１
- タイムキーパー（司会）２

これが１チームで、主、副の2チーム。

タイムキーパー２は居ない場合もありうる。

（特に他に行く部屋がなければ、待機中のチームもいるとなお良い）
# タイムキーパー（司会）は…
- 主にリーダー以外がやる
- 司会業なので、発声練習や、読み上げの練習をしておいてください
- タイムキーパーが二人いるな時は、適当に交代してください
#### トーク前に
- 登壇者に**「お名前と、トークタイトルの読み方をおしえてください」**と聞いて読み方を確認する
- **「今回時間の経過は途中でおしらせしませんので、ご自身でペースを調整してください。時間終了時には『お時間です』とお伝えします。トーク終了後は壇上で待っていてください、質問がある聴講者がいればはなしかけていただきます。もし良い質問で、なにかお礼以上の事をいいたければ、質問内容を復唱してから、マイクでしゃべってください」**と伝える
- どのマイクをつかうか聞き、マイクを登壇者に渡す（登壇者が自力で持ったら問題なし）
- 登壇者がプロジェクタに接続できるようにサポートする
- 人がよほど少なくないかぎりは**「本日は大勢の方がいらっしゃいますので、できるだけ前の方から間を開けずにつめてお座りください、電源は床にございますが、譲り合ってどうぞ」**とアナウンス
#### トーク開始時
- （ほぼ）開始時刻になったらアプリからチャイムがなるので、そうしたら開始
-  **「時間となりましたので始めさせて頂きます、○○さんによる、○○です、宜しくお願いいたします、皆さん拍手をおねがいします」**
#### トーク中
- 舞台横に座っていること、離れる時はルーム監視員と交代
- 時間になると、時間割アプリが鳴るので、そこで**「お時間です」**と一言伝える
- マイクが弱いようなら、音量操作
#### トーク終了
- **「ありがとうございました、みなさん拍手をお願い致します。登壇者の方はもうしばらくそのままでいてください。皆さん質問やあるいはよかったよという感想などあれば是非前の方に歩いてきて登壇者さんとお話ください。トークは終了しておりますので、移動する方はどうぞ移動下さい。」**とアナウンス
- もし、登壇者が質問をマイクで復唱しないようならば、**「すみません、質問内容をマイクで復唱してからお話いただけますか」**と言う。
- この間に次の方と調整しておく
- 次のトーク5分前になってもトークがおわっていない等でプロジェクタにPCをつないでいたら、マイクで**「もうしわけございませんが、次のトーク時刻が迫っておりますので交代をお願いします」**と問答無用で降壇（プロジェクタを次の人に渡す）させる。
- 質問＆雑談自体は、用意ができていれば次の時間ぎりぎりまでそのまましてもらってOK
#### マイクについて
- マイクが不調なら、すぐに自分のものを渡す。電池切れなら低い方の登壇台の下に充電器があり、そこに交換用の電池があるのでそれと交換。
- 壇上マイクは電源不要で両手が空くのでおすすめ
- ピンマイクの電源スイッチはフタの中なので、一度あけてOnにして渡す
#### 不適切なトークについて
- トーク内容が不適切ならば、遮って**「すみません、今の表現は不適切と思えます」**と警告する。不適切が続くようならばトークを中断させ、終了させる。Slackにその旨を書く。むずかしければエスカレーション
- まあ、はりきらなくていい。よほどのことでなければ止めなくてもかまわない。
- 「不適切」の判断は別途記載  [#43: 不適切とは]
#### PC接続について
- もし可能なら、画面が4:3の時は**「4:3ですが、大丈夫ですか？」**と訊く
- 登壇者が変更にこまっている場合には、 [#66: Macの調整方法]の内容をおしえてサポートする
# ルーム監視員は…
- 主にリーダーがやること、目配せすること
- 整理整頓とイレギュラーな人に注意するのがお仕事
- 困っている人がいたら手助け
- 注意してもダメな人がいたら、即エスカレーション
- ツイッター担当や、現地の人から指示がはいればエアコン操作
- 後ろの方に居て、マイクが弱いようなら、音量操作を指示する
- TKが緊急的にトイレにいきたい場合などは一時的に交代する
- Slackを見ておく
- Twitterもできれば見ておく
- 照明は「プレゼン１」で固定だが、どう考えても見えない場合には「プレゼン２」に落とす
- 後ろにはあまりたまらせないこと。どうしても立って見たい人はいるので「入り口を開けておきたいので、すこしズレていただけますか？」といって壁にそわせたりする
- 地べた座りは許すが、できるだけ邪魔にならないように前方に誘導
- 部屋が一杯になったとおもったら、Slack経由でツイッター担当に「もう一杯だよ＞＜」とかツイットしてもらう
- 「部屋が一杯」とは、椅子が全部うまるくらい
- 入場規制は「これはなにかあったら事故があるな」と思うくらい人がきたら入り口で「申し訳ございませんが、この部屋は一杯です、是非他のトークをご覧下さい」等と言う
- 無理はしなくてよいです。
- もし照明を変えたなら、照明をプレゼン１に戻すこと
- タイムキーパーはアプリがやるが、万が一の為にたまに時計を見る
- タイムキーパーが交代要請したら交代
#### トーク終了後
- 椅子や机が荒れていれば、適当に直す
#### 忘れ物について
- 「忘れ物」をみつけたら、トークの合間にタイムキーパーにもっていって休憩時間に忘れ物ではないか？とアナウンスさせる
- 即みつからなければ、スタッフ控え室に持っていく
- 忘れ物を「何部屋でみつかった」とツイッター担当に渡す [#32: スタッフ担当箇所リスト, #41: ネット担当心得]
#### トラブルについて
- けが人などがでたら、自力で歩行できれば控え室につれていく、あるいはuzullaやMyfinder、makamakaなどのコアスタッフを呼ぶ
- こぼした、よごした系は#staff で＠here 当てにSlackで助けを呼ぶ
#### リーダーはSlackを注視してください
- できればイヤフォンマイクをつけておくとか、自分のroomについてはSlackのNotificationを常時にしておくとか、設定してください。

---
# 資料
#### 照明
- 休憩中も、発表中も、常に [プレゼン1]。

![image](https://cloud.githubusercontent.com/assets/870716/15804754/ac89f48c-2b4e-11e6-9994-928e747fa6d0.png)
#### エアコン
- 自由に操作してよい。リーダーはツイッターで苦情があれば操作する
- とはいえ、暑い寒いは個人差があるので、多少自分で判断すること（暑いがでてもおかしくないが、寒いがでたらなにかおかしい）

![image](https://cloud.githubusercontent.com/assets/870716/15804752/a1ecf7c2-2b4e-11e6-89cd-11cf549b4474.png)

**Comment by myfinder** [comment]
マイクの電池は、低い方の登壇台の下に充電器があってそこに交換用の電池がありますのでそれで交換してください。

**Comment by timakin** [comment]
細いですが、当日HNの読み違いとかあったら気まずいので、
講演前には読み方の確認とかを本人にしておくと良さそうですね！

**Comment by uzulla** [comment]
電池オペ追記done

**Comment by mass10** [comment]
撮影は禁止ではないが、あまり激しくパシャパシャとやるのはご遠慮いただく、的なスタンス... かな。
“スライドを公開するつもりか” をスピーカーに予め確認し、「スライドは公開されますので、頑張って撮らなくても大丈夫です」 とアナウンスしてあげたいところ。

> #31

**Comment by mass10** [comment]
前の方のライトを消す、とかの操作方法は朝確認しておきたい。

**Comment by mass10** [comment]
「後ろの方聞こえてますかー」 をちゃんとしてあげたい。

**Comment by uzulla** [comment]
@mass10 

撮影に関して、良い感じのが思いつけば、アナウンス文章を是非つくってください！

照明は、上の方の写真にありますが、1箇所でまとめて操作できるので、今度の現地確認でみてみてください。当日朝確認も必要ですね

＞ 「後ろの人きこえてますかー」

それ系の良いガイドライン、思いつく感じでしたら是非作成してください！
先程本repoのコラボ権限飛ばしましたので、本ISSUEの１番目の投稿や、WikiにかいてもらってOKです。

**Comment by mass10** [comment]
##### トーク中の写真撮影につきまして
- トーク中の写真撮影は禁止ではありませんが、周りの方々への配慮を宜しくお願い致します(あまり激しくパシャパシャとやるのはご遠慮ください)。なお、スピーカーによってはトーク資料を公開してくださる方もいらっしゃいますので、見逃した部分は後ほどご確認いただくことも可能かと思います。スライドが公開予定かどうかを確認したい場合は、トークの開始後でも遠慮なくご質問ください。
- 「写真撮影NG」や「撮ってもいいけどインターネットに公開しないで」など、スピーカーに対する撮影可否にも様々なケースがあります。スピーカーへの配慮も併せて宜しくお願い致します。注意事項があればスピーカーの方から最初にアナウンスされることが多いですが、もし不安でしたらスピーカー本人へ遠慮なく質問してください。

**Comment by uzulla** [comment]
👍

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E3%83%88%E3%83%BC%E3%82%AF%E9%83%A8%E5%B1%8B%E9%81%8B%E5%96%B6
Wikiに転記した
