### ISSUE TITLE
エントランス入館受付心得

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#40]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E5%8F%97%E4%BB%98%E6%8B%85%E5%BD%93-%E6%A5%AD%E5%8B%99%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB

に転記されました

**Comment by hasegawa-tomoki** [comment]
これ、間違ったひとに渡す案件が必ず発生する気がする。
つまり、「本当に正しく来た人の入館証が無くてその人が入れない」というのが発生する訳で、そういうときのフローは考えておきたいですね。
（会場中から探し出す…のは無理だよなあ…）

**Comment by isuka** [comment]
場内アナウンス的なものがあれば、「○○さんのカード持っている人いませんか？」みたいに出来ませんかね？
落とし物の落とし主を探す時にも使えると思いますし。

**Comment by mass10** [comment]
「並べておいて自分のを自分で取る」方式は

**Comment by mass10** [comment]
カードも一緒に渡すから絶対ダメですね

**Comment by myfinder** [comment]
間違った人に間違った名前で渡してしまった場合は会場から探し出す必要がありますね。要注意です。
もし発生しちゃったら遊撃部隊に "◯◯の名前の入館証持ってる人探して連れてきて" とslack等で連絡すれば良いかと思います。

**Comment by uzulla** [comment]
追加で出来そうな当日の多少の工夫としては、入館証にConnpassのIDを紐付けておく（渡す前に書き込んでおく）くらいですかねえ。
IDかいておいて、ソートしておけば、束から渡すときに探すのもはやくなりそうではある

**Comment by uzulla** [comment]
まあ、だだっぴろい会場に2000人いるわけではないので、もしそう言う事が発生したらところどころでアナウンスして聞くオペレーションとします。

**Comment by myfinder** [comment]
登録状況を見ていると "7/2しか登録していないのに7/3も来ちゃう" 人が現れる可能性が大いにありそうで、その場合発生が想定されるのが ”前日の入館証でそのまま入ろうとする人” です。
そういう人がいた場合は当然ながら入館いただけないので、受付時の注意事項として考慮いただけますようお願いします。

**Comment by uzulla** [comment]
受付マニュアルにさらに追記しました。

また、タスクとして、抽選日より前に複数会、「１日しか登録してないとかないよな？」とConnpassのメッセージ機能経由で言います。いま、一本ながしておきました。

**Comment by myfinder** [comment]
届いておりました、ありがとうございます！

**Comment by myfinder** [comment]
入館受付時に、机を出せないのでバインダーとかを使うと思うのですが、これはお貸しいたします。

**Comment by kikumoto** [comment]
> IDかいておいて、ソートしておけば、束から渡すときに探すのもはやくなりそうではある

これは実際どれくらい現実的でしょうか？
当日に書いている時間があるのかどうか。可能なら前日までに終わらしておきたい気もします。
ただ、これができないと朝のピーク時に人をさばいていくのが厳しそうに思えるから、この事前作業をどうやるかですね。
事前準備できているとして、朝のピークは受付窓口５つにして、下一桁（0と1, 2と３...）で分類できている状態にできればなんとかなりそうですかね。

**Comment by uzulla** [comment]
@myfinder 私は前日に品川入りするんですが、そのときに私ががんばってソートしたり、Connpassの番号を入館札に書き込むことはできますか？

**Comment by hasegawa-tomoki** [comment]
~~「入館証をバイネームで出すかどうか検討中」ということだったと思うのですが、それによってすごく変わってきますね。~~
バイネームに決まってた。しっけい。

**Comment by myfinder** [comment]
@uzulla 可能です。いらっしゃるタイミングは個別に調整しましょう。前日できる準備はお手伝いします。

**Comment by uzulla** [comment]
@myfinder 
「バインダー、ボールペン」は何個お借りできますか？（特にバインダー）

**Comment by myfinder** [comment]
いくつ必要ですか。詳細な個数は数えていないので明日確認したく。

**Comment by uzulla** [comment]
@myfinder 
一番うれしいのは10個だとおもいます。あと、サンプル画像いただけるとたすかります！

**Comment by myfinder** [comment]
はーい

**Comment by myfinder** [comment]
@uzulla こういうやつで、10個以上ありましたのでそれを当日お貸しします。
![image](https://cloud.githubusercontent.com/assets/74346/16034681/08a12352-324e-11e6-8061-8fc8c6dbf224.png)

**Comment by uzulla** [comment]
よさそうですね！大変ありがとうございます！

**Comment by keima** [comment]
ここまでの流れをGDocsでマニュアル化しました。当日不運にもいきなり受付担当を命ぜられてもなんとかなるようなあたりを想定しつつ書きました。
（最終的にGitHub Wikiにまとめるので似非Markdownで書いてます）
https://docs.google.com/document/d/1TIsc8H_pCoJWYVK3wmRAK0vH3ZqFxr8UP2GVw1wXnRQ/edit?usp=sharing

（ダブルメンテになるからやめろ、など含めて）ツッコミ歓迎。以下疑問点。
- 集合時間、設営開始時間、受付の開始時間が不明（少なくとも僕はまだ把握しておりませぬ。。）。
- 受付の終了予定時間が不明（ずっと居れや、ってなってもまぁ仕方ないか）
- 受付方法における「connpass受付票・名簿」と「Microsoft入館証」のひも付けについて
  - "マルチスレッド化する方策"と関係してくるが、そろそろ決めたい。 @uzulla 
  - ↑のマニュアルでは「受付窓口では番号によって窓口を変えるとかはしない、入館証は『募集枠』別に分割でまとめられて置いてある」を個人的に妄想している
  - 「登壇者枠 1束(26枚)」「LT枠 1束(16枚)」「スタッフ枠 1束(40枚)」「一般参加 3束(130枚)」「遠方枠 1束(20枚)」「飛び入りトーク枠 1束(10枚)」のような感じ。

「うっせーな今考えてんだよ！」ってことであればすいませんすいません 😈

**Comment by kysnm** [comment]
最終的には @uzulla さんご意見を伺いたいですが

> 集合時間、設営開始時間、受付の開始時間が不明（少なくとも僕はまだ把握しておりませぬ。。）。

集合時間、設営開始時間は置いておくとして、受付開始は人数規模から言って 1 時間前の 9:00 には始めたい気がします (タイムテーブルが 9:30 からになってはいますが…)

> 受付の終了予定時間が不明（ずっと居れや、ってなってもまぁ仕方ないか）

以前 Slack で 15時くらいには引き上げても大丈夫と聞いています
あとは状況次第かな… 最低でも一人残れば良いような気がします？ (それでもツーマンセル？)

https://gist.github.com/kysnm/58031c6cc0527f8b84d3d3eb5a6a8d9b

(余分な会話も含まれてますが 💦 )

あと GDocs についてですが、受付は最大 10 人と聞いています。想定としては受付担当 6 人 + 遊撃 4 人にくらいになるんじゃないかと思います
人員割り振りを考えると 受付 3 列 (ツーマンセル)、誘導各列 1 人で計 3 人、ゲート前誘導 1 人くらいかなと思います
人の流れは当日にならないとわかりませんが、おそらく9:50 から 10:10 の 20 分間と 12:50 から 13:10 の 20 分間に波がある事が予想されます
内容的にはちょっと受付担当者のやる事の分量が多すぎるし、初めてやる方には難しい気がします
声を出すのが苦手な方もいると思いますしね

個人的な意見としては、ピークを考えると受付自体は一人でもオペレーション出来るようにした方が良いじゃないかなーと思います
(余裕があれば二人一組でやった方が正確なのは間違いないですが)

あと列的にスピーカーは分けた方が良いかもなーとうっすら思っています
(開始時間に駆け込みがあっても困るし)

以上、ざっくりと感想でした。ご意見、反論お待ちしております

**Comment by isuka** [comment]
> 集合時間、設営開始時間は置いておくとして、受付開始は人数規模から言って
> 1 時間前の 9:00 には始めたい気がします (タイムテーブルが 9:30 からになってはいますが…)

タイムテーブルの時間は仮置きなので気にしないでもらって大丈夫です。時間決まったら反映します。

あと、docsでTODOになっていたメンバーのタイムテーブルは[書いてあったリンク先](https://docs.google.com/spreadsheets/d/1QlwF2rwvY9-TOn9IyGgq_LLsDSYCPviAkTpBZWxM8uM/edit#gid=1876396116)で管理していく予定です。

**Comment by uzulla** [comment]
>  1 時間前の 9:00 には始めたい気がします 

そうしましょう！

> あと列的にスピーカーは分けた方が良いかもなーとうっすら思っています

あーでもまあその例外をかんがえるのは相当なので、声がけで「急いでる人は言ってください、割り込みさせます」っていうだけでいいんじゃないですかね。

**Comment by uzulla** [comment]
> "マルチスレッド化する方策"と関係してくるが、そろそろ決めたい。 @uzulla

これ何回か打ち合わせで話したけど書いて無かったですね。

## 事前準備

・事前に入館証の裏にCONNPASSのIDを全部記入しておきます（uzullaが前日作業）
・その入館証の束を、末尾番号で10束にわけます
・その束は穴をあけて、ヒモかなにかに通してひとくくりにしておきます

## 当日

・受付に立つ人は、最大10人になります（前述の通り10束しかないので）
・末尾番号を来訪者に確認させ、それぞれの担当者のところにならばせます。
・来訪者は担当者に相対したら、番号をみせます（印刷orスマホ画面）
・ソートしておくので、がんばってサーチ（これはがんばるしかないが、所詮一束20枚しかないので）
・番号がみつかったら、本人に「アンケートに記入した本名」をなのらせて、その入館証の名前と一致するか確認
・ヒモの穴をちぎって渡す、「あなたのお名前ですね？」と本人の名前と相違ないか本人にも確認させる。
・なんかアナウンスするならする

### 人数縮退時は

末尾123までは〜とか、奇数なら〜とか適当に人数に応じてやってください。

**Comment by uzulla** [comment]
帳簿の消し込みかんがえてたんですけど、どうせ入館証がマスターだからいらないなってなりました。
繰り返しになりますけど、入館証はとても大事です。

**Comment by uzulla** [comment]
> あとは状況次第かな… 最低でも一人残れば良いような気がします？ (それでもツーマンセル？)

まあ、ツーマンセルが一番いいですよね（トイレいきたい！水がほしい！とかあるでしょうし）

何時に引き上げるかは議論の余地があって、まあ最後までのこしておきたい気もしますし、さすがにLTからくる人はいないだろともおもうし、どうでしょうね？

**Comment by uzulla** [comment]
> 受付は最大 10 人と聞いています。

これはスレッドが10という意味でいったので、誘導の声出し係が必要なら、さらに追加します。

**Comment by kysnm** [comment]
> その束は穴をあけて、ヒモかなにかに通してひとくくりにしておきます

これ一番気になっています
どの位置で止めるのかによって誤って QR コードを破くという恐怖心が違うので

> 帳簿の消し込みかんがえてたんですけど、どうせ入館証がマスターだからいらないなってなりました

これは同意です。
入館証の残りを数えないと入場者数がわからないのが若干気になりますが、かと言って代案も無いな

> まあ、ツーマンセルが一番いいですよね（トイレいきたい！水がほしい！とかあるでしょうし）

そうですねー。ただいなかったら twitter で呼んでねというのがありならもう少しゆるくても良いかなと思いました

> 何時に引き上げるかは議論の余地があって、まあ最後までのこしておきたい気もしますし、さすがにLTからくる人はいないだろともおもうし、どうでしょうね？

個人的な感覚として他のイベントでは LT 前の最終セッションで締切としています
(他のセッションを一本も見ずに LT だけ参加というのもどうかと個人的には思ってしまいます)

> これはスレッドが10という意味でいったので、誘導の声出し係が必要なら、さらに追加します

正直部屋担当もギリギリだと思うのでそこまでする必要があるかどうかちょっと疑問です
今回のうずらさん、まいんだーさんの思いは十分理解していますが、普段 MS さんで行われる夜の勉強会に来た事がある人にとってはだいぶ感覚が違いそうなので
(場合によっては物江さんが一人で入館証を配っている場合もありますし)

**Comment by kysnm** [comment]
> これはスレッドが10という意味でいったので、誘導の声出し係が必要なら、さらに追加します

要するに私の意見としては、そこまでガチガチに決めずともピーク時 10 並列で最低限の案内だけして迷っている人がいたら手近な人が案内するで十分じゃないかなーと思っています

**Comment by kysnm** [comment]
> docsでTODOになっていたメンバーのタイムテーブルは書いてあったリンク先で管理していく予定です

との事なのでとりあえずこれは乗っかりましょう

**Comment by uzulla** [comment]
> これ一番気になっていますどの位置で止めるのかによって誤って QR コードを破くという恐怖心が違うので

たてにながいんで、下の余白に穴開けます。

![_2016_06_21_1_25](https://cloud.githubusercontent.com/assets/870716/16202094/35ac1978-374f-11e6-9570-a61b30bc0417.png)

> そこまでガチガチに決めずともピーク時 10 並列で最低限の案内だけして迷っている人がいたら手近な人が案内するで十分じゃないかなーと思っています
> 正直部屋担当もギリギリだと思うのでそこまでする必要があるかどうかちょっと疑問です

そこはおまかせします！
「出せるよ」（どこまでスケールさせられるよ）というのがこちらの話しで、いらないといわれたら別にかまわないので！

> ただいなかったら twitter で呼んでねというのがありならもう少しゆるくても良いかなと思いました

これもかまわないです。Twitterでよんでね、は有りです。
ただ、入館証の束をだれがもってるのかよくわからん、どこにあるのかよくわからん、というのだけは避けたいですね。

担当がそこにいれば、かならずそこの人がもっているわけですし。

> 入館証の残りを数えないと入場者数がわからないのが若干気になりますが

別に途中で入場者数を数える必要もないので大丈夫です。

**Comment by uzulla** [comment]
基本的に、 kysnmさんがやりたいようにやってもらえればよいです。私がこうだとおもう、というのは普通にハネてもらってかまわないです。

私は「資源をできるだけ提供します！10人以上いります？」「入館証の管理だけはしっかり！」「あと、俺が思うにこういうのがいいのでは？」ということをいっているだけで、経験者のkysnmさんを信頼しております！なので、そこで適当にkysnmさんにしきってもらってよいです。

ただ、最終的に、「我々はこうしたぞ！」というのを後世にのこしたいので、まとまっているとうれしいのと、書けない（？）ことや、暗黙的な所は少なめで、シンプルになるとうれしいです。

**Comment by kysnm** [comment]
> 別に途中で入場者数を数える必要もないので大丈夫です

あ、これはこちらの問題で縮退などを考えるのに入場者数がどんな状況かを把握する必要があるという事でした

> ただ、最終的に、「我々はこうしたぞ！」というのを後世にのこしたいので、まとまっているとうれしいのと、書けない（？）ことや、暗黙的な所は少なめで、シンプルになるとうれしいです

この辺実は経験者で私より若くフットワークの軽い @keima さんに期待しておりまして、たたき台を作ってもらいこの場で議論したという流れです
うずらさんの持っている情報もだいたい拾えたと思うのでこれはこれで良かったのではないかなと思っております (お手数おかけしてしまいすみません 🙇 )
まだ何か不足している情報があるとかこうした方が良いとかのご意見をお待ちしております @keima さーん

**Comment by uzulla** [comment]
なるほど！了解です。 keimaさんも受付ベテランなのですね期待！！

**Comment by kysnm** [comment]
各部屋のスピーカーが到着していない際に受付に問合せが来る可能性があるので、受付番号と connpass アカウントの組の資料は欲しいかもです
(connpass アカウントとタイムテーブルのお名前が一致していない可能性があるとは思いますが…)

**Comment by uzulla** [comment]
> 受付番号と connpass アカウントの組の資料は欲しいかもです

了解です作ります

> connpass アカウントとタイムテーブルのお名前が一致していない可能性があるとは思いますが…

これは絶望的に一致してないですね（苦笑）

**Comment by isuka** [comment]
タイムテーブルにアカウント名の一覧シートを追加しようと思っているのでcommpassアカウントも並べるようにしましょうか？
commpassアカウントとgithubとかのアカウントの紐付け情報ってuzullaさんしか持ってないです？こちらで見られる物があれば突き合わせやりますよ。

**Comment by uzulla** [comment]
@isuka

> commpassアカウントとgithubとかのアカウントの紐付け情報ってuzullaさんしか持ってないです？

そのようなリストは無いです。

（レギュラートークで応募漏れしてる人がいないかを付き合わせましたが、特に必要を感じ無かったので、そのときにリストは作成していません）

**Comment by isuka** [comment]
@uzulla 
ああ、ごめんなさい。参加者一覧見ればとりあえずスタッフは拾えますね。
人力ですが。(白目)

**Comment by uzulla** [comment]
すまんな…すまんな…

**Comment by keima** [comment]
身に余る役割を仰せつかった keima です、よろしくお願いします :bow:
ちなみにベテランではないっす・・・まだまだ勉強中の身ですが頑張ります(｀･ω･´)ゞ

ひとまずは「[うずら案](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/40#issuecomment-227163878)」でマニュアルを構築していきます。
6/27に抽選結果が出るので、それまでにマニュアルをだいたい作成できていればいいな。
（作業の都合上）

また何かあればお知らせします。

**Comment by uzulla** [comment]
@keima どこでつくるかによりますけど、issueやdocsやwikiでつくってくれるなら随時見ます！

**Comment by keima** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E5%8F%97%E4%BB%98%E6%8B%85%E5%BD%93-%E6%A5%AD%E5%8B%99%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB
Wikiに受付マニュアルを作成しました。
本issueのdescriptionの変更などお願いします m(_ _)m

**Comment by uzulla** [comment]
転記しました（コラボレーターなら修正できるのでは？）
問題なければCloseしちゃってください

**Comment by keima** [comment]
（あっコラボレーター貰う前に開いてたからアイコン見えてなかった。。。）
close!
