### ISSUE TITLE
ネット担当心得

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#41]
## 必須
- Twitterで、全部のハッシュタグを監視する
  - クレームを処理する
    - 「WifiのAPがわからん」とかにレス
    - 冷房系＞部屋リーダーにSlackで連絡
    - 暗い、明るい＞部屋リーダーにSlackで連絡
- Slackを監視する
  - Slackで呼びかけに反応がない場合、担当に電話する
  - 「ネット班、○部屋に伝えてくれ」的なのがきたら、いって伝え、つたえました、とSlackに書く。
- 忘れ物受付
  - 届いたらシャメってSlackに流す、何の部屋でみつかったかも記載する
  - Twitterに「テキストで」説明を書いて流す
  - 財布、携帯などは安易に開けないこと
  - 人がとりにきたら、その人の同意の上で本人確認する
    - まず入館証をチェックし、名前と受付番号をSlackのpriv_staffに書き込む
    - 財布＞身分証明書などと突き合わせ
    - 携帯＞パスコード解除ができるか
    - そういったものができないもの＞特徴をちゃんと言えるか
  - みつかったら、Slackのポストを編集してみつかりましたという
  - ツイッターにも「○○みつかりました！」とポストする
  - 「明らかなゴミ」でもそれは落としものとしてあつかう
- slack経由で「A部屋一杯です！」みたいな情報がきたら、そのようにツイートする
- slack経由で「A部屋緊急事態！」みたいなのがきて、遊撃隊、あるいはuzullaがみてないようなら電話する。
- 最低一人は控え室にいること（落とし物のオペレーションがあるので）
## できれば
- Hashtagを監視して、よさげなツイッターをみつけたらRTする、Favする
- （できる人がいれば）togetterを作る
  - 最初からつくっておくと楽なので…
- スマホのSlackで、全部の通知で音がなるように設定しておくと便利（Tips）
- 公式サイト更新の可能性があるので、jekyll の操作をおぼえておくこと

**Comment by myfinder** [comment]
入館証を記名式にしようと思っておるので、忘れ物対応時は入館証を確認、という手順で良いかと思います。

**Comment by uzulla** [comment]
「名前をきいて」というのを、入館証をみせていただいて、に変えました。

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E3%83%8D%E3%83%83%E3%83%88%E6%8B%85%E5%BD%93%E9%96%A2%E9%80%A3
Wikiに転記した
