### ISSUE TITLE
遊撃隊の心得

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#42]
- 一人で行動OK
- 主にホワイエなどを周回する
- トイレにも忘れ物が多いので、自分が用足しするときなどには一応チェック
- 常時Slack、Twitterに目を光らせる
- へんな行動（アルコール摂取や、入ってはいけない箇所にはいっていたら即注意）
- ゴミをゴミ箱に捨てている人がいたら「ゴミは全部持ち帰りです」と言う、小競り合いになるかもなので、もしゴミ箱の中にはいっちゃったなら、拾い上げるまではしなくて良いが…。
- うるさい人がいたら注意
- うるさいの定義とは、声がセミナールームに聞こえるかどうか
- 注意がこわければエスカレーション
- 廊下に怪しい人がいたら「どうしました？」と声掛け
- ルーム監視員に「どうです？」とか聞いたりする
- 必要なら、速やかに一時交代する
- ケガなどで、ルーム担当から引き渡されたら控え室に案内
- 「落とし物」があれば控え室に持っていって対応
- 困っている人がいないか、怒ってる人がいないか目配せ、いたらSlackへ
- こぼれた、よごれた系が発生したら、メインで対応する

**Comment by hasegawa-tomoki** [comment]
こういうのはオッサンの方が良いだろうから自分やりましょうか。

**Comment by isuka** [comment]
私もやりますよ。

**Comment by mass10** [comment]
僕もここっぽいです

**Comment by t-kaga** [comment]
自分も撮影しながら可能な範囲でコレやります。

**Comment by myfinder** [comment]
ゴミ箱は重たいので無理に移動させる必要はないと思いますが、たくさん捨てられると大変なので禁止ではなく、あくまで"ご協力お願いします"という姿勢で問題ありません。

**Comment by uzulla** [comment]
@hasegawa-tomoki さんは、当座部屋リーダーやってほしいなァ、経験者がちょっとすくないので。
遊撃はいつもはパトロールでしかなくて、みつけたらさっさとエスカレーションでよいので。

**Comment by hasegawa-tomoki** [comment]
OK、部屋リーダーやりまっす。
部屋リーダースレに書いときますね。

**Comment by uzulla** [comment]
ここ、特に発展しないので、Wikiに移動します。
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E9%81%8A%E6%92%83%E9%9A%8A%E9%96%A2%E9%80%A3
