### ISSUE TITLE
不適切とは

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#43]
```
あなたは暴言などをしない常識を持っていて、このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？
```
- 容姿、性差などの差別的表現（やらかす人は大勢いる）
- 壇上や会場で脱衣する、あるいは突拍子もないコスプレなど（希にいる）
- 18歳未満には適切でない性的な表現、暴力的な表現（あまり居ないが、一応）
- 特定のなにかを単に誹謗中傷するなど。批判が比較のための表現ならば扱いがむずかしいが「あの会社はブラックだ」等は好ましくない。
- うつってはいけないものが映った時（パスワードや、第三者の個人情報など）

これらは程度問題であり「これがダメ！」とは定義できないが、「これはTwitterやYoutubeとかにあがったら炎上するな？」とおもったら警告すること。

とはいえ、無理に警告や止める事ができなくてもしかたないので、Slackに「マズイ表現がありました」と連絡すること（把握しておくだけでも重要なので）

そのようなトークであったらトーク終了時に「トーク中に不適切と思われる内容がありました、申し訳ございません」と言う事、しかしこれも無理にいわなくてもOK。ただし、Slackの #priv_staff には共有すること。できるだけどういうことがあったか書いてください。

**Comment by timakin** [comment]
そこまでする必要あるかわかりませんが、前日くらいにslackに#alertとかチャンネル作ってもいいかもしれませんね。
今は打ち合わせ中で穏やかですが、当日はログが混線しうると思うので、
目的別にこう言った連絡は分けたほうが良いと思います。

**Comment by uzulla** [comment]
過去の経験上ですが、仮にalertチャンネルをつくってもなにかが発生すると延々鳴り続ける事になるのでchがオオカミ少年になりやすく、リーダー系やネット担当はpriv_staffを漏らさず見ている（反応がなければネット担当が電話する）、ということで良いとおもいます。

あと、alert系は最初の一報を除いて、けっきょくリーダーや私が直接出向いてリアル対面で判断する事になると思いますので（会場もそんなに広くないですし）

**Comment by timakin** [comment]
おお〜なるほどです。
オオカミ少年になって粗雑になるよりはpriv_staffで一括管理のほうが確かに良さそうですね。
了解です！

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E4%B8%8D%E9%81%A9%E5%88%87%E5%88%A4%E6%96%AD%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
wikiに転記
