### ISSUE TITLE
スピーカーに通知する事柄をまとめる

### ISSUE THREAD

**Issue by hasegawa-tomoki** [hachiojipm/yapcasia-8oji-2016mid#44]
採択通知の時に通知する。
追記する可能性があるのでウェブサイトに掲載して、URLを連絡する。
# 登壇者へのお願い
- 特に「一度もプロジェクタをつかったトークをしたことがない方」は、かならず接続テストをしてください。休み時間、朝、昼休みなどにスタッフにお声がけください。
- 登壇者用の特別なネットワークはございません、会場にはWifiがありますが通信は保証できません。
- 壇上で見せたい機器などは、手持ちできるもの以外は必ず事前にご相談ください。たとえばデスクトップPCやなどといった両手をふさぐほどのものは搬入の調整が必須です。
- 登壇者の方はトーク10分前には会場に来てください。
- 5分前にはプロジェクタへ接続が行えます。（仮に前の人がトーク中であっても）壇上横のタイムキーパーにお声がけください。
- 5分前までにタイムキーパーにお声がけ頂けない場合、枠をキャンセルしたり、別のトークに転用したりすることがございます、ご了承下さい。
- 機器の故障や接続相性など、様々な理由でトーク開始が遅れたり、できなかったとしてもトーク時間の変更や延長はいたしません、申し訳ございませんがご了承下さい。
- タイムキーパーは「終了○分前」などの通知は行いません。ご自身でペース配分をお願い致します。ただし終了時刻に到達した際にはタイムキーパーよりお知らせいたします。
- トークは時間内に終了してください、もしタイムキーパーが終了を指示した際には速やかに終了をお願いいたします。
- トーク終了後は壇上にとどまっていてください。聴講者とのコミュニケーションタイムとなります。
- 次のトーク５分前には必ず次の登壇者の方とプロジェクタの接続を交代していただきます。
- その他、スタッフの指示通りにお願いいたします。
# 設備につきまして
- 会場のプロジェクターにつきまして
  - スクリーンのアスペクト比は16:9
  - 端子はVGAです、HDMIではありません
  - VGA<->Mini Display Port変換アダプタ（いわゆるMacのしっぽ）はございます（ただしMac用であり、すべての機器との互換性は保証できません。可能であればご持参ください）
  - 新型MacBook（USB Type-c）やmicroHDMIなどの変換はございませんのでご持参ください
  - 当日、ノートPCなど発表機材をご用意できない方は前もってご相談ください
- マイクにつきまして
  - 手持ちマイク
  - 卓上マイク（トーク開始前にご相談とテストをお願い致します、ご利用いただけない場合がございます）
  - ピンマイク（トーク開始前にご相談とテストをお願い致します、ご利用いただけない場合がございます）

**Comment by myfinder** [comment]
Macも調整すれば16:9になりますよ。

**Comment by uzulla** [comment]
> でもアナログVGAなのでMacにつなぐとたぶん4:3で映るよ

これホント？VGAでも普通に16:9うつるよ

**Comment by myfinder** [comment]
いくらMicrosoftだからってそれなはいwwww

**Comment by uzulla** [comment]
@hasegawa-tomoki 
スピーカーに通知する事柄をまとめるスレに変更しました、
○分前に来てくれ、コネクタはこうだ、などをまとめていきます。

**Comment by uzulla** [comment]
http://yapcasia8oji-2016mid.hachiojipm.org/for_talker/

作成したのでクローズ
