### ISSUE TITLE
2日目の打ち上げ的なパーリーナイト

### ISSUE THREAD

**Issue by makamaka** [hachiojipm/yapcasia-8oji-2016mid#45]
たぶんここのことであってる？
http://tabelog.com/tokyo/A1314/A131403/13028112/

20時～貸し切りの方向でよいかな？

---

http://connpass.com/event/33945/

**Comment by myfinder** [comment]
そうです、そこです！
他のコミュニティとかのイベントでもよく使われております。

**Comment by uzulla** [comment]
あとでまた説明しますけど、19時くらいからでいいんじゃないかなとおもっております。

**Comment by uzulla** [comment]
こちら、予約するならはやめが良いのでは（あるいは予約しない？）

**Comment by makamaka** [comment]
忘れてた……
19:15ぐらいからでよい？

**Comment by uzulla** [comment]
コース料理というわけではないとおもうので、何時間居られるかによりそうですね。
ダブリナーズ…この間渋谷でいきましたね、これならキャッシュオンですよね。

2時間で追い出されるなら19:15で良いですが、もし3時間とかつかえるなら終了直後の19:00からでよいのでは。

**Comment by makamaka** [comment]
では居られる時間の確認含めて19時の方向で進めます。

**Comment by uzulla** [comment]
一昨年のHUBがそうだったとおもうんですけど（もしかして嘘かも）、貸し切りの時間がおわったら、そのまま通常営業に移行できるとたすかりますね。（つまり、貸し切りでなくなるが、追い出しもない）

**Comment by makamaka** [comment]
確認しました。
19時から2時間貸し切り可。延長は30分毎に1人につき500円
貸し切りの保証費用  120,000円
ビュッフェ方式となり予め料理は決まったものが出る。
料理は5品～8品で 1800円、2000円、2500円、3500円のコース
飲み放題は　2000円コース　生エビスのみ、ウィスキー、ワイン、カクテル、焼酎
　　　　　　2500円コース　ビール4種　ビアカクテル、梅酒が追加
てな感じです。
入れ代わり立ち代わりでお願いできるか聞いたけど、上記の体系にしかならんとのこと……
とりあえず検討ということにしました。どうしましょうね？

**Comment by uzulla** [comment]
人数は最大何人ですかね？また、人数確定はいつまででしょう？

**Comment by makamaka** [comment]
最大は60人です。
あー確定締日については確認してないです。

**Comment by uzulla** [comment]
・確定締め日は知りたいですね！あと、貸し切りは何人からでしょう（HPには「貸切 可 （20人～50人可、50人以上可）」とかあるな…日本語がよくわからんけど）
・保証費用は、実費と相殺ということでよいのでしょうかね？前払い？
・料理と飲み放題を合わせて、一人4000〜5000円ですかね(組み合わせで変動ですよね)

5000円をまた僕が握手して回収して回るのか…まあいいけどｗ

**Comment by makamaka** [comment]
確認しました。
予約締め切りは6/19（日）です。
貸切なので人数は何人からでも構わないとのこと。
保証金は売り上げが12万超えれば不要。
金額はそうですね、3800～6000円の組み合わせになりますのでそんな感じかと。

**Comment by uzulla** [comment]
なるほどシステムがわかりました！

12万ということは、仮に4000円として、30人くれば大丈夫ですな！

**Comment by makamaka** [comment]
ですです。

**Comment by uzulla** [comment]
http://connpass.com/event/33945/
つくりますた。

**Comment by uzulla** [comment]
とりあえず予約してしまってもらえますか？

**Comment by makamaka** [comment]
了解しました。

**Comment by makamaka** [comment]
予約しました。
あとコースの決定を今週末までに。

**Comment by uzulla** [comment]
まあ、食べ物1800＋飲み物2500のにしますかね。
（でも細かいの出るのイヤだな）

**Comment by uzulla** [comment]
俺のおつり労力と、計算のしやすさを鑑みて、ここは2500+2500=5000円にしよう。500円で悩みたくないでござる。

**Comment by makamaka** [comment]
承知！

**Comment by uzulla** [comment]
connpass書いた。
とりあえず30人いけば俺が自腹らなくていいので、懇親会よりよほど気楽だ…。

**Comment by uzulla** [comment]
こちら、店側にコミットしたら一応おしえてください〜。

それでタスク的におわったならば、Wikiに転記して、CloseしちゃってOKです。

**Comment by makamaka** [comment]
19日に人数確定（お昼ぐらいでよいかな）→店に連絡、で完了の予定です。

**Comment by makamaka** [comment]
現時点で35人です。この人数で確定にしようと思います。

**Comment by uzulla** [comment]
はい、よろしくおねがいします。

ちなみに、当日ふえるのはNGなのか追加料金で大丈夫なのかきいておいてください。

**Comment by makamaka** [comment]
人数増えるのは15時までならok、とのことです。

**Comment by makamaka** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/7%E6%9C%883%E6%97%A5%E3%81%AE%E6%89%93%E3%81%A1%E4%B8%8A%E3%81%92

に記載。 closeします。

**Comment by uzulla** [comment]
15時かー、なるほど。

Connpassの募集日数を調整して、当日もアナウンスしますかねえ（っていうタスクをたててもらってもいし、まあ35いればええやんという見方も出来るな）

**Comment by makamaka** [comment]
募集日数調整＋アナウンスしましょう。タスク立てておきます。
