### ISSUE TITLE
設営作業

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#47]
- 1,2日目、両日で設営は必要です。
- 封鎖系
  - ゴミ箱封鎖（養生テープで）
  - 冷蔵庫封鎖（養生テープで）
  - C横の、ホワイエの流しと自販機封鎖（養生テープで）
- 掲示系
  - EVホール突き当たりにA4さしこみ
  - クラウディアさん設置x2
  - ルーム名の掲示、立て看板に差し込む
- 動画撮影のセットアップ
- 15分以内には出来る想定

---

設営スタッフは以下を予定しております

@hasegawa-tomoki （封鎖係
@kkotaro0111 （掲示物貼りだし係＆動画
@papix （社員（紙製）を大事に扱う係り
@uzulla（主に指示だし＆動画
@myfinder （チェックと、社員（紙製）のアテンド

（どの方も、サブ班のはず）
（もし暇そうな人がいたらその場でナンパします）

**Comment by myfinder** [comment]
はい、立て看板も磁石どめなので差し込めばよいです。

**Comment by uzulla** [comment]
🙆

**Comment by myfinder** [comment]
設営は1日目、2日目両方とも必要なのでそれも忘れないよう作業リストを作っていただければと。

**Comment by mass10** [comment]
##### タイムテーブルの貼り出し
- どこか一か所に大きく全タイムテーブルを貼る？ (紙 or ホワイトボード)
- 各ルームのドアにタイムテーブルを貼る？(A4)

**Comment by uzulla** [comment]
タイムテーブルの貼りだしはしません。
というか、一切の紙類は配布しません、みんなスマホでみてもらいます。（あるいは印刷持参）

ただし、スタッフ側には適当にくばるかもしれないですねー。

---

Q：なぜ紙をくばらないのか？
A：はじめてペーパーレス（ただしゼロ枚とはいっていない、シュガーレスのようなもの）のカンファレンスを開きたいから、エコ！

Q：本当の所は？
A：紙を印刷するのはお金がかかるし重いし締切があるし誤字で悲しくなるしみんなそこらに捨てて回収面倒だし、なによりこれ以上カンファレンスの度に指を切りたくないから。

**Comment by mass10** [comment]
あっ、問題ないですね

**Comment by uzulla** [comment]
設営は、まあ２〜３人くらいいればできるかなって思うんですけど、どなたか我こそは設営！という方いらっしゃいますか？
設営はルームと時間かぶらないので、

・養生テープの扱いにたけている
・物を大切にあつかえる
・こういうのやったことあるか、得意だ

という方、是非。

**Comment by mass10** [comment]
いろいろやります

**Comment by hasegawa-tomoki** [comment]
設営やりますよー
（日曜は朝イチトークだけど、まああまり関係無いであろう。）

**Comment by mass10** [comment]
メモ: 撮影チームの椅子とか三脚とかのセットアップ

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E8%A8%AD%E5%96%B6%E4%BD%9C%E6%A5%AD%E9%96%A2%E9%80%A3
Wikiに転記した
