### ISSUE TITLE
撤収手順をまとめる

### ISSUE THREAD

**Issue by hypermkt** [hachiojipm/yapcasia-8oji-2016mid#48]
## 業務内容
-  会場片付け
  - 会場内の落し物・ゴミを収集 => 控室に集める => Twitter報告
  - 椅子、設備を片付ける
  - マイクを揃えて、TK席にあつめておく
  - 電気を消す
  - 会議室の空調を止める
- 撤収作業
  - 掲示物を全て回収する
  - 封鎖の養生テープを全部剥がす
  - 録画機材回収
  - 社員（紙製）の回収
-  追い出し誘導
  - 31Fエレベーター前担当
    - エレベーターに乗るのを案内する人
    - ドアが開いたら速やかに誘導する
    - 一人でも入れる余地があったら「あと◯人入れます」と案内する
    - 満員になったら「ドアを閉めてください」と伝える 
  - 2F受付担当
    - 入館証を回収する
      - ポストは穴が小さくて大変なので、スタッフが手でうけとる、人の波がとぎれたらポストへ。
      - 入館証は2日目も使えると勘違いする人もいるかもしれないので「できるだけ」回収する。
    - 改札から出たら速やかにエントランスの外に誘導する
    - エントランスをでてすぐのデッキにもあまり貯まらないように「ご協力をお願い」する（強制していやな気分になってもらいたいわけではない）
    - 待ち合わせたい場合には（もし、雨天だと心苦しいが）二階くだってビルの間の公園がいいですよと誘導する
### 「なぜかゴミが出た」
- ありえないはずのゴミはわすれものかもしれないので、捨てずに全てスタッフ控え室に集める
### しないこと
- 懇談会への誘導
- 「Connpassの情報をみてください」
### 担当の部屋が片付いたら、自分の荷物をまとめて自分も撤収用意する

---
## 担当者
- 「会場片付け」＆「退場お願い」班 ＞ ネット班と撤収作業員以外全員
- 撤収作業 ＞ 後述の撤収作業スタッフ
- 31F EVホールの誘導 ＞ 1〜2名（適当にその場で決めます
- 出口誘導班
  - 2F EVホール（受け取り） 2名 ＞ 受付班より
  - 2F エントランス 2名 ＞ 受付班より
- ネット班は、片付けしつつ有り難うございました的文面をつぶやく（可能ならtogetterを保存）
#### 撤収作業スタッフ

@hasegawa-tomoki （封鎖係剥がし
@kkotaro0111 （掲示物とりはずし＆動画機材を撤収
@hypermkt （社員（紙製）を大事に撤収
@uzulla（主に指示だし＆動画
@myfinder （チェックと、社員（紙製）のアテンド

（他にも、もし暇そうな人がいたらその場で徴用します）
#### 完全追い出し班

@uzulla（蛍の光を歌う役
@myfinder （丁寧においだしていただく役
#### 懇親会先発隊

@makamaka 
@papix

**Comment by karashi39** [comment]
決めることを大枠で分類すると、

[1日目]
・会場片付け
・会場から人間の追い出し
・懇親会の誘導
・たむろってしまう人の誘導

[2日目]
・会場片付け
・会場から人間の追い出し
・たむろってしまう人の誘導
・打ち上げ(あるのか？)

という具合でしょうか？

**Comment by uzulla** [comment]
懇親会の誘導は特にやりません。そこに割くマンパワーはないし、みんなオトナだからね！

お世話になった会場から速やかに、漏れ無く、事故事件なく、解散していただく事です。

**Comment by isuka** [comment]
完全撤収の確認って必要or可能なんでしょうか？
変な階にスネークしてる人がいたりしたらとか。

**Comment by myfinder** [comment]
細かい点ですが、受付は2Fです。
あと、1日目2日目ともに入館証は回収という形になるので、入館証ポストがボトルネックになるためそれのケアもできれば考慮に含めておいて欲しいです。

**Comment by myfinder** [comment]
入館証回収する用の箱でも用意しますかね、社内で余ってる箱とか出すので。

**Comment by myfinder** [comment]
回収は必須ではないのですが、2日目も使えると勘違いする人がでてめんどくさいかなと思いまして。

**Comment by hypermkt** [comment]
> 入館証回収する用の箱でも用意しますかね、社内で余ってる箱とか出すので。

エレベーターから見て左側しか箱が無かったと思うので、確かにもう一つ（右側？）用意してあるとスムーズに退場できそうな印象です。

> 回収は必須ではないのですが、

なるほど。ということは退場時に入館証が無い場合はそのまま通してもよろしかったでしょうか？

> 2日目も使えると勘違いする人がでてめんどくさいかなと思いまして。

ありえそうですね。可能な限り回収するように案内するようにします。

**Comment by hypermkt** [comment]
受付は2F、入館証は入館証ポストに回収するのを案内する旨を追記しました。

**Comment by uzulla** [comment]
@isuka 

> 完全撤収の確認って必要or可能なんでしょうか？ 変な階にスネークしてる人がいたりしたらとか。

不法侵入（不退去）を試みるような方はいないでしょうが、いたとしてもあのビルの内部セキュリティはシッカリしているということなので、我々が可能な範囲でご帰宅を確認できれば十分だとおもいます。

よって、私＋myfinderさんが最後責任をもって一周します。
みなさんには「モウイイヨ」といいますので、それをきいたら速やかに帰宅or懇親会へどうぞ。

（他の階に隠れるとか、あり得ないような人の相手はセキュリティや警察の方におねがいしましょう 👮  )

**Comment by uzulla** [comment]
@keima さんと @kysnm さんへ
受付班で、EV誘導と受付での入館証回収OPをおねがいしたいのですが、大丈夫ですかね？

**Comment by kysnm** [comment]
@uzulla 
返信遅くなってすみません
EV 誘導って 2F のみで良いのでしょうか？
31F も？

**Comment by uzulla** [comment]
31Fはいいです。2fのみ。
31Fは誰かその時暇そうな人に頼むことにします。

**Comment by kysnm** [comment]
@uzulla 
cc: @hypermkt 

うす
人員の指定ってありますか？
まあ 5 人もいれば十分かな
あ、description に書いてあった 2 人ですね

要はゲート前の一番狭い箇所、文字通りボトルネックを解消すれば良いのだと思っています。
回収箱の前に張り付いて案内するとそこの流れが悪くなりませんか？

もう少し人員を配置して回収箱を複数用意するか、当日限りの入館証である事を案内したうえで持ち帰って個別に破棄していただくでも良いような気がします

(懇親会の誘導ここに書いてあったのか… 🙇 )

**Comment by uzulla** [comment]
まあ、そんな大量にいなくてもいいとおもうんで（短時間ですし）ツーマンセル２チームでいいのではないでしょうか。
余った人は31Fのお手伝い、くらいで。

> 回収箱の前に張り付いて案内するとそこの流れが悪くなりませんか？

「回収」についてなんですが、箱につっこもうとすると時間がかかるわけで、
最終的に回収箱にはいってればいいだけだから、あれの前に人が立って、人が手でうけとっていけばいいんじゃないですかね。

あそこにこまごまいれようとせず、両側で手で受け取るだけで速度がガンとあがるとおもいます。そもそもEVがそこまでスループットでないので、それくらいで十分でしょう。

**Comment by uzulla** [comment]
つまり、あの自動改札の手前のゴミ箱と、その反対側で二人でならび、EVが到着したら「こちらから退出ください、入館証はよろしければお渡しください」と声掛けしたらいいと思います。
31FのEV前で、「入館証を回収しますので、用意しておいてくださいね！」って声掛けもしましょう。
（それでもみつかんない！とかいう人は「じゃあいいですよ」と声掛けて、そのまま帰ってもらう）

で、その二人がうけとった束は波が引いている間にまとめて捨てる。

（で、改札の外、エントランス自動ドアあたりにもう２人がいて、「たまらないでね！」と声掛け）

**Comment by kysnm** [comment]
> ツーマンセル２チームでいいのではないでしょうか

了解です。4 人という事ですね

> 「こちらから退出ください、入館証はよろしければお渡しください」と声掛けしたらいいと思います

ああ、これは description が間違っているのですね。やはり可能な限り回収で良いと
というわけで description 修正お願いします @hypermkt さんかな？

EV がひっきりなしに来る事もなさそうなので、案内は流れに応じて臨機応変にで良いですね
(基本的に入館証回収にあたって、人が溜まってきたら追い出しくらいで良いかなーと思っています)

**Comment by uzulla** [comment]
> 基本的に入館証回収にあたって、人が溜まってきたら追い出しくらいで良いかなーと思っています

基本それでよいのですが、エントランスやデッキとかに「貯まられると困る」というのがあります（迷惑をかけたくない）。入館証回収よりそっちが実質的には重要だったりします。

なので、声掛けと、声掛けしてもどうしても喫茶店の前あたりにいそうなのを、どうにかできればな、という感じです。

**Comment by uzulla** [comment]
> というわけで description 修正お願いします @hypermkt さんかな？

こちら修正しました。

**Comment by uzulla** [comment]
@kysnm さんにこのrepoのコラボ権限をinviteしました。
なにかあればDescription修正していただいてOKです。

**Comment by kysnm** [comment]
なるほど、了解しました。会場に迷惑にならないようにという事を念頭に対応します

**Comment by uzulla** [comment]
まあ、それはあくまでお願い、という感じで。（ニュアンスがむずかしい）

**Comment by uzulla** [comment]
Desc、すこし修正しました。

**Comment by kysnm** [comment]
description 見ました
- 会場利用者として会場提供者の迷惑にならないように
- 参加者に楽しい気持ちのまま帰ってもらえるように
- あくまでも協力していただくスタンスで

というところでしょうかね

**Comment by hypermkt** [comment]
すいません、確認が遅れました。修正ありがとうございます！内容確認しました。担当ぎめまでありがとうございます。

**Comment by isuka** [comment]
タイムテーブルに撤収の人を反映しました。
makamakaさんとpapixさんて7/2だけであってますか？

**Comment by makamaka** [comment]
そうですね、7/2だけで大丈夫です。

**Comment by isuka** [comment]
了解です。

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E6%92%A4%E5%8F%8E%E9%96%A2%E9%80%A3
Wikiに転記した
