### ISSUE TITLE
サイト：トーク募集中をクローズする

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#49]

**Comment by karashi39** [comment]
#1のお知らせを必ず読めという応募ルールがあるので、本気で締め切ったタイミングで、#1に「トーク応募は本気で締め切りました。LTはこの日まで」と書いて、それ以降の応募は問答無用でクローズする、という感じでしょうか。GH使い慣れていないので、もっと簡単で便利な方法があるのかもしれませんが私はまだ知らない(教えてください

**Comment by uzulla** [comment]
これはサイトの話しなので、GHではないです。
私が作業するので大丈夫です。

**Comment by uzulla** [comment]
サイトなど、書き換えたのでクローズ
