### ISSUE TITLE
タイムテーブルの方に「決定」ラベルが欲しい

### ISSUE THREAD

**Issue by makamaka** [hachiojipm/yapcasia-8oji-2016mid#53]
https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues
「1日目決定」「2日目決定」みたいなラベルがついてると有り難いなと。
（面倒であるなら権限もらえれば時間あるときにポチポチ貼っていきます。）

**Comment by uzulla** [comment]
あれ、権限なかったでしたっけ、付与しときました！
是非おねがいします！

**Comment by makamaka** [comment]
権限どうもです！
了解ですー

**Comment by makamaka** [comment]
1日目 26、2日目 29。
たぶんあってるでしょう。というわけでclosed！
