### ISSUE TITLE
Connpassのメッセージ機能経由で言うタスク

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#57]
- 「１日しか登録してないとかないよな？」
- 「キャンセルするならいま！チケットの譲渡はできないぞ！」
- 「ウッカリきても本当に入れないぞ！」
- http://yapcasia8oji-2016mid.hachiojipm.org/venue_info/ を見よ、という

---
- [x] 抽選数日前に「お忘れではないですよね？」とか言いつつながす
- [x] 抽選日前々日に「キャンセルするなら今！」とか言いつつ流す
- [x] 抽選日に「今日は抽選日ですね！」とかいいつつ流す
- [x] 7/2 開催日前に「開催ですね！」とか言いつつ流す
  - [x] 開場は9時、9:50ごろ開会、10:00トークスタート
  - [x] 「会場書注意みてね！特にConnpassの画面をもってきてね！」
  - [x] 「登壇者心得を見てね！」 
  - [x] タップ持ってきたほうがいいよ
  - [x] 懇親会繰り上がりあるけど、みんな大丈夫か？
- [x] 7/3 開催日前に「開催ですね！」とか言いつつ流す
  - [x] 開場は9時、9:50ごろ開会、10:00トークスタート
  - [x] 「会場書注意みてね！特にConnpassの画面をもってきてね！」
  - [x] 「登壇者心得を見てね！」 
  - [x] タップ持ってきたほうがいいよ
  - [x] もし空きがあれば、打ち上げの宣伝も

**Comment by kysnm** [comment]
経験上、受付で数人は connpass のアカウントがわからないという人がいるので、前日にアカウント確認のお願い (一度ログインしておいてもらうとか) と受付票をご用意くださいとか書いておくと良いかもです (それでも数人は見落としている)

入館証の確認も合わせてお願いしておくと良いかもですね。間違いに気づいたらスタッフか受付にご連絡ください的な
(定期的にアナウンスした方が良さそうなので #39 とかにも書いておいた方が良い？)

**Comment by uzulla** [comment]
「Connpassを用意せよ」についても記載した

http://yapcasia8oji-2016mid.hachiojipm.org/venue_info/

こういうページがあるので、毎回このURLをはっつけておくろうとおもいます！
（なにか不足があれば指摘ください〜）

**Comment by kysnm** [comment]
なるほどー
ページの内容については問題ないと思います

ただリンクだと一手間増えるので本当に大事な事は直接書いた方が良いかもとも思います
(前日一回で良いので)

**Comment by uzulla** [comment]
まず一通確認的なのをCONNPASSから流した

```
主催のuzullaです
なんとヤパチー開催は来週末！みなさんいかがお過ごしでしょうか。

ここで念のための各種おしらせをお送りいたします。必ずご確認ください。
（二日登録されている方には二通届きます、すみません）

## キャンセルをわすれていませんか？

実はその後予定がはいってしまって参加できなくなった…
そういったことはありませんか？
その場合、是非きちんとキャンセルをご協力ください！


## 通し券はありません！

二日間なら、２つのconnpass登録が必要です。
そして日付をお間違えではないですか？間違えていると入り口で帰る事になります！

（後、懇親会も二日目はまだまだ空きがございます
　http://connpass.com/event/33945/ ）


## 当日はconnpassの受付番号がわかるように、印刷などを！

入場時にconnpassの受付番号を確認させていただきます。
（間違えない為にも、番号を口頭でのべたり、メモはやめましょう）
connpassの番号がわかる印刷やスクリーンショットをお持ちください。

確認方法につきましては、以下公式サイトの
「当日はConnpassの受付表をご用意ください」節をご確認ください。

http://yapcasia8oji-2016mid.hachiojipm.org/venue_info/


## 会場情報、諸注意

会場設備の説明や、諸注意などは以下のURLでご確認ください。
当日も紙などは配布いたしませんので、こちらをご覧頂きます。
是非公式サイトはスマホ等にブクマして来場ください。

http://yapcasia8oji-2016mid.hachiojipm.org/venue_info/


## LT登壇者の方、LT枠へ登録変更されましたか？

今一度お知らせスレをご確認ください。
一般参加抽選枠のままですと、落選した場合は登壇者であっても当日入場ができません。

https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/1#issuecomment-226678076

ご面倒ですが、是非お早めにお願いいたします。

## レギュラー、LT、共通の登壇者の方へ

プロジェクタのアスペクト比など各種情報をまとめておりますので、ご確認ください。
特にMacにおいてプロジェクタとの相性が発生するかもしれません。Macの方は是非ご確認ください。

http://yapcasia8oji-2016mid.hachiojipm.org/for_talker/


以上です、宜しくお願いいたします！
```

**Comment by makamaka** [comment]
次回　キャンセルするなら今！　について
「抽選日以降キャンセルが出ても追加の抽選はないので」
という点を強調しておく必要があるかなと思いました。

**Comment by uzulla** [comment]
了解です、次回にはかこうとおもます。
ただ、それの意味する所をみんなわかってくれるかな…。

**Comment by uzulla** [comment]
まかまかさんのコメントを参考にしながら、ラストコール的なのをなげた

**Comment by uzulla** [comment]
ちょっと送るの遅れたけど、とにかく送ったのでクローズ
