### ISSUE TITLE
登壇者が参加登録わすれていないかチェックする

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#58]
- [x] 7/2
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/16
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/49
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/59
- [x] 7/3
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/10
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/5
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/30
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/44
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/46
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/67
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/84
  - [x] https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/90

---
- [x] 参加登録して！と通知する
- [x] ついでに http://connpass.com/event/33945/ を伝える

**Comment by myfinder** [comment]
私の分は登録しました！

**Comment by uzulla** [comment]
全員分を確認したのでCloseします
