### ISSUE TITLE
タイムキーパーは機械にやらせるぞ

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#59]
「人間が時計を注視するのはむずかしいのでは」という意見があると聞いた、まことに正論だとおもった。

部屋の運営のために、全体的なアラーム（チャイム？）がほしいな、という話しです。
- みなのスマホにアラームをめっちゃ沢山設定する（効果的だが大変では）
- 部屋に一個づつ、アラームを大量にセットした専用のスマホを置く（わりと現実的そう、みんなスマホ余ってるでしょ）
  - 一律アラーム音はうるさそうだが、適切に音を場面でわけて設定すれば…？
- twitter/slack にBotをたてて皆に通知する（楽だがワンショットでは気付かない可能性は？）
- 部屋に「タイムキーパー君」と名付けたPCを設置してsayさせる（ちょっとコードかけばできそう）
  - なんなら開始の挨拶もsayさせればいいのでは（読めない名前がありそう）

---

https://itunes.apple.com/jp/app/school-chimes/id1023234803?mt=8

を使おうと思います、iOS端末が三つ必要。
- [x] uzullaのipad
- [ ] morizoooさんのiPad
- [ ] motchangさんのiPad

---
- [x] タイムテーブルをつくって、設定する

**Comment by hasegawa-tomoki** [comment]
個人的には、常に残り時間が表示されていると、途中でペース配分出来て好きです。
突然「チーン！」とか言われると動揺する、というのもあり、残り時間はあった方がいいんじゃないかな～。
（最終的には好みの問題と思いますが。）

**Comment by uzulla** [comment]
たぶんそれは「トーカーが知る為のタイムキーパー」という話だとおもうのですが、それの設備（たとえば、iPadをトーカーが見える所に置く）を用意するのはむずかしいですねー。
机にアナログ時計があるので（あるいは皆さんご自身のスマホで）がんばってください！という感じがします。

ちなみに、ここでの主語は「部屋担当」であり、「運営のためのトーク開始時間を忘れる」とかそういうやつです。
「それがタイムキーパーの仕事だ！」といわれればそうなんですけど、そこの負担を軽減したいなって感じ。

**Comment by uzulla** [comment]
あと、これは本当に個人的な経験からなんですけど、「○分前」って札、ホントにみんなみてます？ｗタイムキーパーやってたときに、しばしば見てもらえなくて何分もかかげてたりしたし、そしてトーカー側になったとき俺は見た事が無いｗ

**Comment by uzulla** [comment]
http://www.amano-tec.com/apps/schoolchimes.html
これ最高では？（試し中）

**Comment by hasegawa-tomoki** [comment]
ああ！なるほど！
「～分前」は自分はあんま見てないっす。時計があればそれを見るし、なければ手元に時計を用意するので。

学校チャイム、いいですね。

**Comment by uzulla** [comment]
http://www.amano-tec.com/apps/schoolchimes.html
https://itunes.apple.com/jp/app/school-chimes/id1023234803?mt=8
アプリ試した

👍
- アプリ終了してても起動してくれる（かなり重要）
- 時間割は何パターンか設定できる
- 今が何の時間なのか表示できるし、残り時間もでる
- iPadなら、すくなくとも目の前にいるタイムキーパーが気付く程度の音量はだせそう
- iPhoneにも対応
- 無料、広告が出るだけ

👎
- 学校のチャイムと、サイレン（ウウゥ〜〜！という甲子園のあれ）、鐘の音しかない。自前の音には変更不可能
- 時間割それぞれに違う音は設定できないので、終了５分前通知にはつかえなさそう（たとえば、全部チャイムになる）
- ローカルプッシュをつかった？「着信音」なので、iPadの場合は音量がかわらなかったらコンパネをひらく必要がある
- 絶対時間指定なので「急遽5分ずらす」とかは無理
- 横画面対応してない

まあでも全体的にいって、よくできてるとおもう

**Comment by uzulla** [comment]
１台はmorizooo さんにかりられることになった

**Comment by uzulla** [comment]
@motchang さんにもかりられることになった。
電源もおねがいします！

**Comment by uzulla** [comment]
@morizooo さんも当日電源もお願いしますね！

**Comment by uzulla** [comment]
@motchangさんと @morizoooさん、
https://itunes.apple.com/jp/app/school-chimes/id1023234803?mt=8

のアプリをいれて、動くか確認しておいてください。

あと、シングルアプリモードへの設定（と解除）をおぼえておいてください。
https://support.ubiregi.com/archives/675
（あるいは、特定多数のTKにさわられても良い状態（たとえば初期化）にしてあれば、シングルアプリモードは不要ですが）

**Comment by morizooo** [comment]
軌道確認しましたが、ipad proだと拡大できず、解像度が半分になりそうです(音はでました)
時間割設定は当日でしょうか？

**Comment by uzulla** [comment]
@morizooo 
なんとiPadProなのですねすごいｗ

解像度がかわらないのはiPhoneAppだからだとおもうのでしかたないとおもいます。音がでればOKです。

時間割設定は、やり方をなんとなくおぼえていてくれれば当日朝でOKです。

**Comment by uzulla** [comment]
非常にうまく回った。アプリ落ちも僅か。
これは最高の結果だと思う。

入力はしんどいが、まあ気合い入れればどうということはなかった。
