### ISSUE TITLE
ボランティアスタッフ打合＆キックオフ懇親会 No2

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#60]
http://connpass.com/event/33968/

---
- [x] 店を予約 http://tabelog.com/tokyo/A1314/A131403/13170829/

---
- [x] 初めての方に、改めてエアコンと照明とマイクのあたりを説明
### 以下担当のみ
- [x] あのときのMacで4:3はまぐれだったのか一応確認
- [ ] エントランスの写真などをあらためて撮っておく
- [x] コンビニ最短ルートチェックなど
- [x] ビルの狭間空き地へのルートチェック
- [x] shinpei氏のカメラ本体 + ACアダプタを受け渡し
- [x] SDカードを持っていってチェック（uzulla
- [x] ビデオカメラの暗所チェック
- [x] カメラの暗所チェック
- [x] 撮影用、アングルとカメラの焦点距離についてチェック（24ー300mmくらいで）
- [x] AEDへのアクセスルートチェック
  （他なにか思いつく事があればISSUEに追記お願いします）

**Comment by hasegawa-tomoki** [comment]
- AEDへのアクセスルートチェック

とか？使える階段あるのかな。EV使うしか無いのかな。

**Comment by myfinder** [comment]
31Fと30Fにはフロア内階段があります。前回共有したフロアマップを参照ください

**Comment by hasegawa-tomoki** [comment]
右下あたりの階段ですね！

![default](https://cloud.githubusercontent.com/assets/3850359/16065237/eefc8c84-32e3-11e6-8e0a-d731a3aa9660.png)

**Comment by myfinder** [comment]
@hasegawa-tomoki yes that's right!!

**Comment by mass10** [comment]
可能であれば附室-1の確認

**Comment by uzulla** [comment]
終了したのでClose
