### ISSUE TITLE
宴会大臣の募集

### ISSUE THREAD

**Issue by makamaka** [hachiojipm/yapcasia-8oji-2016mid#61]
懇親会担当のmakamakです。
7/2の懇親会は会場となる店に伝えておく携帯番号が二つ必要でして、そのためもう１名、宴会担当（電話番号）を募集します。
あと7/2はイベント終了後急いでお店の方にいって、来る人の誘導的なことや場を暖めるなども一緒にお願いしたく。
ぜひよろしくお願いします！

**Comment by makamaka** [comment]
担当が決まりましたのでcloseします！

**Comment by uzulla** [comment]
誰になったんですかね…

**Comment by papix** [comment]
@uzulla 私が担当させて頂くことになりました! がんばります!
