### ISSUE TITLE
ステッカー用のロゴの制作

### ISSUE THREAD

**Issue by silfsquare** [hachiojipm/yapcasia-8oji-2016mid#64]
# 3の流れより。

直径60mmのシール台紙を使用。

**Comment by kkotaro0111** [comment]
![seal](https://cloud.githubusercontent.com/assets/1256392/16170735/0b2f985e-3598-11e6-8212-4176aaca58e4.png)
こんな感じ？

![seal_ol](https://cloud.githubusercontent.com/assets/1256392/16170736/228aa4e4-3598-11e6-831e-4310a46bfe88.png)
データとしてはこんな感じしてあるけど、どうだろう。
納品仕様があれば教えて下さい

https://dl.dropboxusercontent.com/u/3703508/seal_ol.ai
AIデータです。

**Comment by silfsquare** [comment]
いいとおもいます！

**Comment by kkotaro0111** [comment]
なぜかassignersリストに @silfsquare が出てこない

**Comment by uzulla** [comment]
それはこのrepoのコラボレーターではないからだな
一応Inviteリンクをsilfsquare におくったので、Acceptしたら設定できるようになります。

**Comment by kkotaro0111** [comment]
Issue名は「ロゴ制作」だから、これ、Closeしてもいいのかな。

**Comment by silfsquare** [comment]
Closeしますー
