### ISSUE TITLE
トーク予定のあるスタッフのシフト調整

### ISSUE THREAD

**Issue by karashi39** [hachiojipm/yapcasia-8oji-2016mid#65]
スタッフの皆様で、トーク・LT・飛び入りLTの予定がある方は  
- その時間休憩をいれる 
- 遊撃隊のどなたかに代打をお願いする
- トークのタイミングをずらす(これはめんどい？)

などが必要だと思いますので  
まずはどなたがどの日の時間にトーク予定があるかを把握させてください。

**Comment by karashi39** [comment]
karashi39  
部屋担当(アルファチームA部屋)  
7/3 LT  (17:25 - 18:50のどこか)

**Comment by hasegawa-tomoki** [comment]
hasegawatomoki
A部屋担当
7/3 10:00-10:30 トーク

**Comment by hypermkt** [comment]
- hypermkt
- A部屋担当 副リーダー
- 7/2 15:40〜16:05 トーク

**Comment by pastak** [comment]
- pastak
- 遊撃
- 7/2 (土) 15:00〜 A会場

**Comment by makamaka** [comment]
・遊撃
・7/2（土） C会場 17:10～18:10 （LT）

**Comment by makamaka** [comment]
あと、tontonの変更をお願いします。

http://tonton.amaneku.com/list.php?id=20160610182539_fCzjm9

**Comment by stefafafan** [comment]
- stefafafan
- 遊撃
- 7/3（日）LT (17:20 - 18:20のどこか)

**Comment by karashi39** [comment]
tontonで管理します
