### ISSUE TITLE
Macだと4:3になる事があるので、設定方法を追記する

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#66]
20160618 に再度確認したところ、プロジェクタが実際16:9で出力できるものの、Macは自動認識で失敗する（選択肢に16:9がでてこない）ことがあったので、手動設定のメモ。

Macのコンパネでディスプレイをひらいて、「変更」をおすだけだと4:3しかでないことがあり、Optionキーをおしながら変更をクリックすると多数の種類がでる。

![_2016_06_19_2_25](https://cloud.githubusercontent.com/assets/870716/16172460/0da3cff6-35c5-11e6-82b0-d0a15d0680fb.png)

なお、運営のおすすめ解像度（？）は~~1280x720~~ → 1280x768

**Comment by uzulla** [comment]
http://yapcasia8oji-2016mid.hachiojipm.org/for_talker/

に追記をおこなった。

**Comment by uzulla** [comment]
登壇者にサイトでアナウンスしたおかげか、あんまり混乱なかったようにおもうんだけど、ルーム担当的にはどうだったんだろう？

**Comment by uzulla** [comment]
なんやかんや、直せる人もいたけど、スタッフがしっていた、ということが強かった模様。
スタッフに周知するのが重要

**Comment by mass10** [comment]
これはマニュアルがあったことが本当に助かった...
