### ISSUE TITLE
ビデオカメラ用の延長ケーブルを買う

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#68]
10mくらいないと無理っぽいので。

https://www.amazon.co.jp/NICOH-%E3%83%8B%E3%82%B3%E3%83%BC-%E3%82%BD%E3%83%95%E3%83%88%E5%BB%B6%E9%95%B7%E3%82%B3%E3%83%BC%E3%83%89-15A10m%E3%82%B3%E3%83%BC%E3%83%89-%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF/dp/B014MB44TU/ref=sr_1_1?s=computers&ie=UTF8&qid=1466271192&sr=1-1

**Comment by kkotaro0111** [comment]
床にあるコンセントからは電源取れないということ？

**Comment by uzulla** [comment]
とれるよ。たんに設置場所を考えるとそうなるな、と言う話しです。

https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/%E9%8C%B2%E7%94%BB%E9%96%A2%E9%80%A3

**Comment by uzulla** [comment]
買った、現地直送

**Comment by uzulla** [comment]
買って届いたのでclose
