### ISSUE TITLE
懇親会の受付と誘導について考える

### ISSUE THREAD

**Issue by kysnm** [hachiojipm/yapcasia-8oji-2016mid#70]
懇親会の受付については @makamaka さん、@papix さんで良いのかという確認
本編の受付担当が入館証の後お金を扱うのはちょっとつらいのでお願いしたいです :bow:

あと懇親会会場までの案内をどうするのかというのも決まっていないと思うので起票しました

よしなにお願いいたします :pray:

**Comment by uzulla** [comment]
懇親会の受付という業務は一切やらなくてもOKです。
お金は、現地で私が席をまわりながら集めます。

誘導は基本的にしません（オトナなんだから、みんなちゃんと来てね！ということで）。
ただ、makamakaさんは早めに行って受け入れ、そしてpapixさんは頃合いをみてゆっくりあるいて(ベストエフォートな）先導をしてもらおうとおもっています。

**Comment by uzulla** [comment]
懇親会は所詮懇親会なので、案内は特にしません。Connpassみて来てね、ということで。

**Comment by kysnm** [comment]
了解です。懇親会のお二人が確認されたらこの issue を close で良いですかね

**Comment by makamaka** [comment]
懇親会、会場からの誘導・受付・集金なしは了解してます。
特に認識に齟齬はないです。

**Comment by kysnm** [comment]
はーい、それでは閉じます
