### ISSUE TITLE
アサインがされていないスタッフさんに人力個別連絡

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#75]
- [x] souhei(sohey)さん
- [x] MAMEDEKAさん
- [x] waterlowさん
- [x] mahoyayaさん

**Comment by isuka** [comment]
waterlowさんRoom A TK2に立候補されました。

**Comment by isuka** [comment]
souheiさん受付にアサイン
mahoyayaさんRoom B TK2にアサイン
未アサイン無し。調整は[#32](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/32)とslackでやります。

**Comment by uzulla** [comment]
doneですね！ @isukaさんありがとうございました！！！！:bow:
