### ISSUE TITLE
前日準備

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#78]
- [ ] 入館証確認
- [ ] 入館証に受付ID記入
- [ ] 入館証束にする
- [ ] 機材最終確認
#### 印刷
- [x] Connpass 受付ID リスト & 登壇者リスト x１部 (機密)（受付班が欲しいとのこと [link](https://docs.google.com/spreadsheets/d/1-10iwmZIVxuLHBXYM-30nbXjHBQzi-43whYfkrOvZ7A/edit#gid=0) ）
- [x] 「本物の緊急時対応PDF」を各リーダー＋スタッフ控え室分印刷 
- [ ] 「A4:大きく数字の書かれた紙（ 0 〜 9 ）  + 予備白紙 6枚」 x1部 （ [link](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/78#issuecomment-229026731)
- [x] トーク部屋むけ スクリプトあんちょこ印刷 x4部 ( [link](https://docs.google.com/document/d/1wF261JEB50TPD4ve_y3tBA_X52ZHLWJ36nVpRl2VwH4/edit) )
- [x] しおり、という名前の連絡帳印刷 x41 部 (機密)( [link](https://docs.google.com/document/d/1j8WXr8TCGGuiP8b4Rf-OlwNBpFKNSc8gxVna7E0-RAM/edit) )
#### done
- [x] 紙に穴をあけるパンチャー (myfinderさんにお願い

他にあれば追加ください

**Comment by myfinder** [comment]
穴はあけ終わりました。

**Comment by keima** [comment]
[【受付】掲示物.pdf.zip](https://github.com/hachiojipm/yapcasia-8oji-2016mid/files/336911/pdf.zip)
作成しました。当初より6枚（念のためのフッターロゴ以外は何も書いてないページ６枚）増えました。
中にPDFが入っていて、１部刷ると16枚でてくるはずです。

**Comment by uzulla** [comment]
@myfinder 
印刷系、まとめておきました（ファイルのリンク先と、部数）
お手数ですが、出力お願いします。

**Comment by myfinder** [comment]
明日の夕方マッタリやりましょう

**Comment by uzulla** [comment]
1830には終わるという夢を見ていた、
人力ソート大変すぎる

id紐付けをできないのかとか、課題が色々ある。
前日作業の後に飲みに行くとかは甘い
