### ISSUE TITLE
LT運営手順書

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#79]
# LT心得
## スタッフ
- リーダー:通常トークと同じ業務
- タイムキーパー:時間をちゃんとはかる
- 銅鑼パーソン: タイムキーパーの指示で楽器を鳴らす,タイムキーパーのそばにいること,「見られている」ので姿勢良く、だらしないのはNGです。可能なら「こういう役目が得意な人」がやったほうがよい。
## 開始前について
- 銅鑼パーソンは銅鑼の試し鳴らしをする。勘違いする人が多いが、銅鑼は楽器であり、精密機器である、力をいれてならすものではない。この時に写真撮影を求められる事があるので、快諾すること。
- 銅鑼や打楽器は叩く強さでなく、叩くフォームが重要である。大きい動作でなめらかに、ゆっくりと自信をもってならすこと。
- 銅鑼はどこかに当たると音がなるので、用意するときにならないように注意すること。
- 銅鑼パーソンが待つための椅子を前においておく（銅鑼は大変に重い）
- LT枠の開始前に、登壇者が全員いるかしらべる。居ない人がいたらリーダーが探す。
- 登壇者に**「これはLTですので、かならず５分、一部の方は10分で終了いただきます。ご協力をお願いいたします、早く終わる分にはOKです」**と言う
- 順序はタイムテーブルに記載された順番
- 通常トーク同様に登壇準備させる
- 自分のスマホのタイマーを５分（一部の方は10分）にセットして用意
- シビアにいくぞ！と自分を鼓舞しておく
## LTなんだけど10分の方が二名だけいらっしゃる
- 以下二名だけLTなんですが10分です、例外的ですみませんが注意してください。
- 7/2 C部屋 nabesinさん「夏のフィッシングまつり」 なお、動画公開不可
- 7/3 C部屋 sugartakerさん「分析ツールのPowerBIで”無料で”社内の作業効率を10倍にした話」
## 手順
- LT開始時刻になったら **「時間となりましたので、これよりライトニングトークを始めます。皆さま拍手をお願いいたします！！」**
- **「でははじめてください！」**でタイマーを回し、トーク開始を指示（名前の読み上げなどは無し）
- タイマーが残り60秒になったら銅鑼パーソンにスタンバイ指示
- 時間になったら銅鑼パーソンは美しいフォームで銅鑼（あるいは打楽器）を叩く（見られているので姿勢良く、笑顔で）
- 銅鑼が鳴り止まぬうちに**「ありがとうございました！では次の登壇者の方おねがいします！」** と言い、準備させる
- 登壇者の準備ができたらすぐに**「でははじめてください！」**と言う、ここまでを繰り返す。
- 全員おわったら **「以上でこのルームのLTは終了です！皆さんもう一度拍手をお願いいたします！xx:xxの閉会式までお待ちください！」**
## 困ったパターンについて
- プロジェクタがうつらない人
  - 3分でうつらなければスキップして後にまわす
  - どうしてもうつらなければキャンセル
- 「たんま！」とかはなし
  - 開始といったら開始なので、まきもどしはなし
- トークを終わらせようとしない人
  - たまにいる、すごく迷惑
  - 問答無用で「おわりました！」と言い、笑顔でプロジェクタを抜きに行く。これはLTのルールである、LTは紳士的な試合である
- そもそも人がきてない
  - スキップする
  - 合間合間に「○○さんいませんか？」と訊く
  - 最後までいなければ「○○さんいませんか？」とよびかけて、いなければキャンセル扱い

**Comment by makamaka** [comment]
えー、LT出ることはあってもタイムキーパーしたことないのに＞＜

とりあえず思いついたことあったら書いてみます。
しかし経験者のかたいらっしゃったらどんどん書いてください！

**Comment by uzulla** [comment]
そうかｗじゃあなんか書きますｗ

**Comment by uzulla** [comment]
C部屋はバリから来た銅鑼があるとして、A部屋どうしようかな…

**Comment by makamaka** [comment]
・TKは登壇者に確認をとったのち、タイムを計り始める。銅鑼叩く人は離れたとこで待機。
・終了1分間前になったらTKは銅鑼叩く人に合図。銅鑼叩く人は登壇者の近くににじり寄る。
・終了時間になったらTKは銅鑼叩く人に合図。銅鑼叩く人は美しいフォームで力強く銅鑼を叩く。

**Comment by uzulla** [comment]
- きびしくいく
- 銅鑼の練習で会場をウォームアップ
- 繋ぎの時間にCM（）

**Comment by uzulla** [comment]
銅鑼、初めての人がたたくと（特に男性は）ちからまかせにたたいて銅鑼がぶっこわれるので、銅鑼リストはちゃんと練習したほうがよさそう。

**Comment by makamaka** [comment]
バリ島の銅鑼、大変重くなってるので、担当者の方は筋力トレーニングで特訓だ！

**Comment by makamaka** [comment]
そういえば前に @myfinder さんが部門の倉庫に銅鑼があったようなって仰ってましたが、結局あれどうなったですかね？

**Comment by myfinder** [comment]
見当たりませんでした。すいません～

**Comment by makamaka** [comment]
おぉ……そうでしたか。
そしたら録音銅鑼音 or ビブラスラップ？

**Comment by uzulla** [comment]
ついにビブラスラップ再登板

**Comment by uzulla** [comment]
レギュラートークとちがって、紹介文はいらないですよね、「始め！」だけでいい。

**Comment by uzulla** [comment]
@makamaka さんレビューおねがいします！

**Comment by makamaka** [comment]
大丈夫だと思います！
一点、「これはLTですので、かならず５分で終了いただきます。～」というのがありますが、LTに10分で申し込んでいる人がいます。これは10分として扱うということで大丈夫？

**Comment by uzulla** [comment]
うっ、nabeshinさんとsugartakerさんのお二人か…、見落としていた。
まあ、二人なら大丈夫かな。

**Comment by uzulla** [comment]
一応書いておいた

**Comment by isuka** [comment]
LTのリーダー、TK、銅鑼PはAとC部屋の担当が引き継ぐ感じですか？

**Comment by uzulla** [comment]
@isuka

そうです。

**Comment by isuka** [comment]
タイムテーブルに反映しました。

**Comment by uzulla** [comment]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/wiki/LT%E9%81%8B%E5%96%B6%E6%89%8B%E9%A0%86
Wikiに転記したのでClose
