### ISSUE TITLE
昼食、弁当を注文したい方スレ

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#81]
まあ、とにかく頼む事にしよう。
https://demae-can.com/shop/menu/1003452/
ここにします。

https://docs.google.com/spreadsheets/d/1yVfkOkTvag4sVlz1god3HeZj97t8DjGDpTMqK14-ZPU/edit#gid=0
ここに適当にかいていってください。

前日までにお願いします。

**Comment by uzulla** [comment]
当方、4〜5人いればピザか弁当を頼むかなとおもっております。
いなきゃ、コンビニかなと。

**Comment by kochizufan** [comment]
両日とも一票加えます

**Comment by mass10** [comment]
両日乗ります

**Comment by mass10** [comment]
お弁当希望

**Comment by pudding666** [comment]
2日目のみお弁当希望です。内容は何でもOKです。
蕎麦激辛以外なら何でも食べます。

**Comment by motchang** [comment]
+1

**Comment by kkotaro0111** [comment]
両日+1

**Comment by makamaka** [comment]
両日 お弁当 +1

**Comment by uzulla** [comment]
これは弁当注文の気運やな、結構店あるなー。

https://demae-can.com/shop/menu/3009851/?blockCd=13103009002
https://demae-can.com/shop/menu/3011233/?blockCd=13103009002
https://demae-can.com/shop/menu/3012598/?blockCd=13103009002
https://demae-can.com/shop/menu/1003452/?blockCd=13103009002
https://demae-can.com/shop/menu/1007407/?blockCd=13103009002
https://demae-can.com/shop/menu/3002559/?blockCd=13103009002
https://demae-can.com/shop/menu/1006410/?blockCd=13103009002

**Comment by silfsquare** [comment]
両日＋１

**Comment by t-kaga** [comment]
両日 お弁当 +1

**Comment by pocket7878** [comment]
両日 お弁当 +1

**Comment by stefafafan** [comment]
両日 お弁当 +1

**Comment by ravelll** [comment]
両日 お弁当 +1

**Comment by mahoyaya** [comment]
両日+1

**Comment by masawada** [comment]
両日 お弁当 +1

**Comment by uzulla** [comment]
どこの店がよいとかありますか？
どこも最低注文金額があるんで、一箇所にまとめてしまいたい。

ざっとみて、ここが一番普通だけど、あまりにも普通。
https://demae-can.com/shop/menu/1003452/?menuCd=a6&firstMenuCd=a6&blockCd=13103009002#menu
ここは安い
https://demae-can.com/shop/menu/3009851/?menuCd=a1&firstMenuCd=a1&blockCd=13103009002#menu

**Comment by mass10** [comment]
コメとおかずがあればなんでもいい感じです

**Comment by makamaka** [comment]
リストみました。
値段とバリエーションから https://demae-can.com/shop/menu/1003452/ に+1します。

**Comment by uzulla** [comment]
受け取りは車止め経由なので、だれか一人（数によっては二人）とmyfinderさんが受け取りにいくことにする。手作り弁当  京香はカード決済、もう一つもAmazon Paymentができるっぽいんで、支払いは先にできるので問題なし。

**Comment by hypermkt** [comment]
両日 お弁当 +1

**Comment by pastak** [comment]
土曜日弁当+1

**Comment by uzulla** [comment]
まあ、とにかく頼む事にしよう。
https://demae-can.com/shop/menu/1003452/
ここにします。

https://docs.google.com/spreadsheets/d/1yVfkOkTvag4sVlz1god3HeZj97t8DjGDpTMqK14-ZPU/edit#gid=0
ここに適当にかいていってください。

**Comment by uzulla** [comment]
7/1 の夕方頃には二日分まとめて注文しますんで、注文をしてほしい人は忘れずにお願いします。

**Comment by myfinder** [comment]
@uzulla 当日は誰かの携帯番号を入れて、車止めについたら電話してくれと注文メモに書いておいてくださればそのように対応いただけるのでよろしくお願いいたします。

**Comment by uzulla** [comment]
了解です。
車止めに向かわせる時にmyfinderさんに声掛けします。

**Comment by uzulla** [comment]
7.2は @makamaka & @pastak くん、遊撃隊なんで、弁当取りに行くのやってくれますか？
7.3は @makamaka & @pupu666 におねがいしようかな。

**Comment by makamaka** [comment]
okです！

**Comment by pudding666** [comment]
了解ですー！！

**Comment by pastak** [comment]
弁当了解です！！

**Comment by moshisora** [comment]
両日 お弁当 +1
（シートには追加しましたが念のためこちらにも）

**Comment by uzulla** [comment]
とにかく終わった。

小銭集めは大変だし、千円とかでバジェット化しないとしんどい。

出前館、前日注文できるけど、ウェブなのに、注文時間のレンジがあった。

**Comment by uzulla** [comment]
誰が唐揚げ好きで、二日連続で唐揚げったかどうかはセンシティブ情報（）だとおもいますので、
Docsの共有範囲をとじておきました。（見たいという奇特な方が居れば言ってください）
