### ISSUE TITLE
各所リーダーにおたのみ申す事

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#87]
- priv_staff だけはSlackの通知をOnにしてイヤフォンなどでかならずみてほしい
- 緊急連絡先（TEL番号がベスト、ダメならLINEでも）をSlackのDMで私におくってほしい
- 緊急連絡先はチームリーダー間とコアスタッフのみで共有されます

---

Slackの通知がかならずすぐになる設定方法（特定のchのみ設定可能）AndroidとiPhone両方版

Android: https://www.youtube.com/watch?v=0zvq6MCqgDA&feature=share

iOS: https://youtu.be/iJpKf3U1d0s

---
- [x] ksynm
- [x] keima
- [x] takkkun
- [x] shimpeim
- [x] hypermkt
- [x] isuka
- [x] raevelll
- [x] masawada
- [x] 62jun62

**Comment by uzulla** [comment]
各リーダー、完了したら一言コメントもらえるとたすかるッス！

**Comment by Shinpeim** [comment]
完了です！

**Comment by motchang** [comment]
ばっちり完了です 💪

**Comment by morizooo** [comment]
OKです！

**Comment by pocket7878** [comment]
完了しました！

**Comment by hasegawa-tomoki** [comment]
OKです！
（通知ディレイの設定はチャンネル単位じゃなくてグローバルじゃないですかね。）

**Comment by hasegawa-tomoki** [comment]
（あ。自分担当外だったか。）

**Comment by uzulla** [comment]
担当外とは(上のチェックは、まだもらってないひとという意味でした

**Comment by hasegawa-tomoki** [comment]
ああ、そうなんですね。
対処済です！BTヘッドセットも買ったのでSPっぽくなる予定。

**Comment by kysnm** [comment]
完了しました！

**Comment by isuka** [comment]
設定完了しました。

**Comment by hypermkt** [comment]
設定完了しました！

**Comment by takkkun** [comment]
設定完了です！

**Comment by ravelll** [comment]
設定完了しました！

**Comment by masawada** [comment]
設定完了しました!

**Comment by uzulla** [comment]
みなさんありがとうございました！
当日、リーダーに紙かなにかで渡す予定です！
