### ISSUE TITLE
MS社員様（紙製）に持っていただく通行止めサイン

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#9]
・二人分必要
・長丁場で、手持ちはむずかしいので首かけで
・ただし、か弱い首に負担などかからぬように軽く
・（できれば）目立つように
・記載内容は取り決めが必要だが、例えば「YAPC参加者の方はこの先通行止め！ご協力感謝します！」とか
・会社ロゴなどは無しで

**Comment by silfsquare** [comment]
@makamaka 
こちら手伝えると思うので明日お話させてください〜！

**Comment by makamaka** [comment]
文面ですが「スタッフ以外立ち入り禁止ですヨ」を考えています。
スタッフよりも「ＭＳ社員」の方がよいでしょうか。

雰囲気を確認するために弊社社員で試してみました。
（確定の際には @silfsquare さんよろしくお願いします。）
![20160617_124625](https://cloud.githubusercontent.com/assets/127601/16141670/2b22bc72-3499-11e6-9c66-034ba914c1db.jpg)

**Comment by makamaka** [comment]
画像でかい……

**Comment by uzulla** [comment]
当日、ヤパチー以外のひとがいるかもしれないんで、ヤパチーってどっっかにかいてないとかなーっておもいますけどどうですかね、どうなんだろう。
@myfinder

**Comment by myfinder** [comment]
文言は問題ないと思います、あとuzullaさんのおっしゃる、ヤパチーってどっかに書いておくというのは、ヤッパチのロゴを右下か左下あたりに入れておけば問題ないのではと考えます。

**Comment by myfinder** [comment]
あと、等身大ポップなんですがもう一つ別のキャラが倉庫から見つかりまして、立つかどうか確認中です。

**Comment by makamaka** [comment]
ヤッパチロゴ、了解です。

**Comment by makamaka** [comment]
メモ
瑠璃の分は京都弁にする

**Comment by myfinder** [comment]
等身大ポップは3体用意できることになりましたので、3体分のご用意をお願いします。

**Comment by makamaka** [comment]
こんな感じになりました。

クラウディアさん用（2枚＋予備）
![01](https://cloud.githubusercontent.com/assets/127601/16178898/37172858-3690-11e6-8200-9ec4757ac7d2.png)

安曇瑠璃さん用（1枚＋予備）
![02](https://cloud.githubusercontent.com/assets/127601/16178899/39da5772-3690-11e6-96f6-a2a60df2d17d.png)

データは約3.4Mなのでメールで送る感じでよいですかね？＞ @silfsquare

**Comment by silfsquare** [comment]
@makamaka メールでもなんでもどんと来いですよ！

**Comment by kkotaro0111** [comment]
ロゴマーク、微妙に色がずれてますね。
そのデータ、まず俺に送っていただけますか？
ロゴ部分直して、再度共有します。

**Comment by makamaka** [comment]
了解です！

**Comment by makamaka** [comment]
データ送ってあるのでcloseします
