### ISSUE TITLE
動画公開

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapcasia-8oji-2016mid#93]
- [ ] メディア集め
- [ ] 取り込み
- [ ] 編集
- [ ] UL

**Comment by uzulla** [comment]
@kkotaro0111 とSDカードコピー会をやるのが一番早いかな？

**Comment by kkotaro0111** [comment]
＠uzulla よし、飲みに行きましょう！

**Comment by uzulla** [comment]
主要なものが大体終わったので、Closeします。
あとは空き時間でちまちまやります。
